[package]
name = "karbeat-dsp"
version = "0.2.0"
edition = "2021"
description = "DSP algorithms and utilities for Karbeat"

[dependencies]
dasp.workspace = true
rustfft.workspace = true
num-complex.workspace = true
log.workspace = true
serde.workspace = true
fastrand.workspace = true
derive_builder.workspace = true
karbeat-macros.workspace = true
karbeat-plugin-types.workspace = true
num-traits.workspace = true
wide.workspace = true
smallvec.workspace = true

[lints]
workspace = true