// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';
import 'api/automation.dart';
import 'api/mixer.dart';
import 'api/monitor.dart';
import 'api/pattern.dart';
import 'api/plugin.dart';
import 'api/plugins/opaque.dart';
import 'api/project.dart';
import 'api/serialization.dart';
import 'api/session.dart';
import 'api/track.dart';
import 'api/transport.dart';
import 'api/utils.dart';
import 'api/waveform.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AudioWaveformUiForAudioPropertiesPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioPropertiesPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BufferDataTypePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataTypePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PluginBufferHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WaveformHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ZeroCopyHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandlePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AudioWaveformUiForAudioProperties
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    dynamic raw,
  );

  @protected
  BufferDataType
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
    dynamic raw,
  );

  @protected
  PluginBufferHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    dynamic raw,
  );

  @protected
  WaveformHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    dynamic raw,
  );

  @protected
  ZeroCopyHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    dynamic raw,
  );

  @protected
  AudioWaveformUiForAudioProperties
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    dynamic raw,
  );

  @protected
  AudioWaveformUiForAudioProperties
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    dynamic raw,
  );

  @protected
  PluginBufferHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    dynamic raw,
  );

  @protected
  WaveformHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    dynamic raw,
  );

  @protected
  ZeroCopyHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw);

  @protected
  Map<int, WaveformHandle>
  dco_decode_Map_u_32_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle_None(
    dynamic raw,
  );

  @protected
  Map<int, AudioWaveformUiForSourceList>
  dco_decode_Map_u_32_audio_waveform_ui_for_source_list_None(dynamic raw);

  @protected
  Map<int, AutomationLaneDto> dco_decode_Map_u_32_automation_lane_dto_None(
    dynamic raw,
  );

  @protected
  Map<int, ModulationLinkDto> dco_decode_Map_u_32_modulation_link_dto_None(
    dynamic raw,
  );

  @protected
  Map<int, UiBus> dco_decode_Map_u_32_ui_bus_None(dynamic raw);

  @protected
  Map<int, UiGeneratorInstance> dco_decode_Map_u_32_ui_generator_instance_None(
    dynamic raw,
  );

  @protected
  Map<int, UiMixerChannel> dco_decode_Map_u_32_ui_mixer_channel_None(
    dynamic raw,
  );

  @protected
  Map<int, UiPattern> dco_decode_Map_u_32_ui_pattern_None(dynamic raw);

  @protected
  Map<int, UiTrack> dco_decode_Map_u_32_ui_track_None(dynamic raw);

  @protected
  AudioWaveformUiForAudioProperties
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    dynamic raw,
  );

  @protected
  BufferDataType
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
    dynamic raw,
  );

  @protected
  PluginBufferHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    dynamic raw,
  );

  @protected
  WaveformHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    dynamic raw,
  );

  @protected
  ZeroCopyHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    dynamic raw,
  );

  @protected
  RustStreamSink<double> dco_decode_StreamSink_f_32_Sse(dynamic raw);

  @protected
  RustStreamSink<PerformanceMetricsDTO>
  dco_decode_StreamSink_performance_metrics_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<UiMixerChannelSnapshot>
  dco_decode_StreamSink_ui_mixer_channel_snapshot_Sse(dynamic raw);

  @protected
  RustStreamSink<UiPluginCommandResponse>
  dco_decode_StreamSink_ui_plugin_command_response_Sse(dynamic raw);

  @protected
  RustStreamSink<UiTransportFeedback>
  dco_decode_StreamSink_ui_transport_feedback_Sse(dynamic raw);

  @protected
  RustStreamSink<UiZeroCopyBufferResponse>
  dco_decode_StreamSink_ui_zero_copy_buffer_response_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioExportConfigDTO dco_decode_audio_export_config_dto(dynamic raw);

  @protected
  AudioWaveformUiForSourceList dco_decode_audio_waveform_ui_for_source_list(
    dynamic raw,
  );

  @protected
  AutomationCurveTypeDto dco_decode_automation_curve_type_dto(dynamic raw);

  @protected
  AutomationLaneDto dco_decode_automation_lane_dto(dynamic raw);

  @protected
  AutomationPointDto dco_decode_automation_point_dto(dynamic raw);

  @protected
  AutomationTargetDto dco_decode_automation_target_dto(dynamic raw);

  @protected
  BitDepthDTO dco_decode_bit_depth_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AudioWaveformUiForAudioProperties
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    dynamic raw,
  );

  @protected
  WaveformHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    dynamic raw,
  );

  @protected
  ZeroCopyHandle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    dynamic raw,
  );

  @protected
  AudioExportConfigDTO dco_decode_box_autoadd_audio_export_config_dto(
    dynamic raw,
  );

  @protected
  AutomationLaneDto dco_decode_box_autoadd_automation_lane_dto(dynamic raw);

  @protected
  AutomationTargetDto dco_decode_box_autoadd_automation_target_dto(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  EffectAutomationTargetDto dco_decode_box_autoadd_effect_automation_target_dto(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  MixerChannelParamTargetDto
  dco_decode_box_autoadd_mixer_channel_param_target_dto(dynamic raw);

  @protected
  ModulationLinkDto dco_decode_box_autoadd_modulation_link_dto(dynamic raw);

  @protected
  ModulationSourceDto dco_decode_box_autoadd_modulation_source_dto(dynamic raw);

  @protected
  Mp3ExportConfigDTO dco_decode_box_autoadd_mp_3_export_config_dto(dynamic raw);

  @protected
  PlaybackModeDto dco_decode_box_autoadd_playback_mode_dto(dynamic raw);

  @protected
  (int, int) dco_decode_box_autoadd_record_u_8_u_8(dynamic raw);

  @protected
  TrackAutomationTargetDto dco_decode_box_autoadd_track_automation_target_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  UiEffectTarget dco_decode_box_autoadd_ui_effect_target(dynamic raw);

  @protected
  UiMixerChannel dco_decode_box_autoadd_ui_mixer_channel(dynamic raw);

  @protected
  UiMixerChannelParams dco_decode_box_autoadd_ui_mixer_channel_params(
    dynamic raw,
  );

  @protected
  UiMixerChannelTarget dco_decode_box_autoadd_ui_mixer_channel_target(
    dynamic raw,
  );

  @protected
  UiParamId dco_decode_box_autoadd_ui_param_id(dynamic raw);

  @protected
  UiPluginInstance dco_decode_box_autoadd_ui_plugin_instance(dynamic raw);

  @protected
  UiPluginTarget dco_decode_box_autoadd_ui_plugin_target(dynamic raw);

  @protected
  UiRoutingConnection dco_decode_box_autoadd_ui_routing_connection(dynamic raw);

  @protected
  UiRoutingNode dco_decode_box_autoadd_ui_routing_node(dynamic raw);

  @protected
  WavExportConfigDTO dco_decode_box_autoadd_wav_export_config_dto(dynamic raw);

  @protected
  EffectAutomationTargetDto dco_decode_effect_automation_target_dto(
    dynamic raw,
  );

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  int dco_decode_i_8(dynamic raw);

  @protected
  KarbeatPluginType dco_decode_karbeat_plugin_type(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AutomationPointDto> dco_decode_list_automation_point_dto(dynamic raw);

  @protected
  List<ParameterSpecDTO> dco_decode_list_parameter_spec_dto(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(int, AudioWaveformUiForSourceList)>
  dco_decode_list_record_u_32_audio_waveform_ui_for_source_list(dynamic raw);

  @protected
  List<(int, WaveformHandle)>
  dco_decode_list_record_u_32_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_waveform_handle(
    dynamic raw,
  );

  @protected
  List<(int, AutomationLaneDto)>
  dco_decode_list_record_u_32_automation_lane_dto(dynamic raw);

  @protected
  List<(int, int)> dco_decode_list_record_u_32_casted_primitive_u_64(
    dynamic raw,
  );

  @protected
  List<(int, int, int)> dco_decode_list_record_u_32_casted_primitive_u_64_u_8(
    dynamic raw,
  );

  @protected
  List<(int, ModulationLinkDto)>
  dco_decode_list_record_u_32_modulation_link_dto(dynamic raw);

  @protected
  List<(int, int, AutomationLaneDto)>
  dco_decode_list_record_u_32_u_32_automation_lane_dto(dynamic raw);

  @protected
  List<(int, UiBus)> dco_decode_list_record_u_32_ui_bus(dynamic raw);

  @protected
  List<(int, UiGeneratorInstance)>
  dco_decode_list_record_u_32_ui_generator_instance(dynamic raw);

  @protected
  List<(int, UiMixerChannel)> dco_decode_list_record_u_32_ui_mixer_channel(
    dynamic raw,
  );

  @protected
  List<(int, UiPattern)> dco_decode_list_record_u_32_ui_pattern(dynamic raw);

  @protected
  List<(int, UiTrack)> dco_decode_list_record_u_32_ui_track(dynamic raw);

  @protected
  List<(int, int, int?)>
  dco_decode_list_record_u_8_casted_primitive_u_64_opt_casted_primitive_u_64(
    dynamic raw,
  );

  @protected
  List<UiClip> dco_decode_list_ui_clip(dynamic raw);

  @protected
  List<UiEffectInstance> dco_decode_list_ui_effect_instance(dynamic raw);

  @protected
  List<UiEffectParameterSnapshot> dco_decode_list_ui_effect_parameter_snapshot(
    dynamic raw,
  );

  @protected
  List<UiEffectSummary> dco_decode_list_ui_effect_summary(dynamic raw);

  @protected
  List<UiGeneratorParameterSnapshot>
  dco_decode_list_ui_generator_parameter_snapshot(dynamic raw);

  @protected
  List<UiNote> dco_decode_list_ui_note(dynamic raw);

  @protected
  List<UiParameterValue> dco_decode_list_ui_parameter_value(dynamic raw);

  @protected
  List<UiPluginInfo> dco_decode_list_ui_plugin_info(dynamic raw);

  @protected
  List<UiPluginParameter> dco_decode_list_ui_plugin_parameter(dynamic raw);

  @protected
  List<UiRoutingConnection> dco_decode_list_ui_routing_connection(dynamic raw);

  @protected
  MixerChannelParamTargetDto dco_decode_mixer_channel_param_target_dto(
    dynamic raw,
  );

  @protected
  ModulationLinkDto dco_decode_modulation_link_dto(dynamic raw);

  @protected
  ModulationSourceDto dco_decode_modulation_source_dto(dynamic raw);

  @protected
  Mp3ExportConfigDTO dco_decode_mp_3_export_config_dto(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  Map<int, AudioWaveformUiForSourceList>?
  dco_decode_opt_Map_u_32_audio_waveform_ui_for_source_list_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AudioWaveformUiForAudioProperties?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    dynamic raw,
  );

  @protected
  WaveformHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    dynamic raw,
  );

  @protected
  ZeroCopyHandle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    dynamic raw,
  );

  @protected
  AutomationLaneDto? dco_decode_opt_box_autoadd_automation_lane_dto(
    dynamic raw,
  );

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  ModulationLinkDto? dco_decode_opt_box_autoadd_modulation_link_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  List<ParameterSpecDTO>? dco_decode_opt_list_parameter_spec_dto(dynamic raw);

  @protected
  ParameterSpecDTO dco_decode_parameter_spec_dto(dynamic raw);

  @protected
  ParameterValueTypeDTO dco_decode_parameter_value_type_dto(dynamic raw);

  @protected
  PerformanceMetricsDTO dco_decode_performance_metrics_dto(dynamic raw);

  @protected
  PlaybackModeDto dco_decode_playback_mode_dto(dynamic raw);

  @protected
  (int, AudioWaveformUiForSourceList)
  dco_decode_record_u_32_audio_waveform_ui_for_source_list(dynamic raw);

  @protected
  (int, WaveformHandle)
  dco_decode_record_u_32_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_waveform_handle(
    dynamic raw,
  );

  @protected
  (int, AutomationLaneDto) dco_decode_record_u_32_automation_lane_dto(
    dynamic raw,
  );

  @protected
  (int, int) dco_decode_record_u_32_casted_primitive_u_64(dynamic raw);

  @protected
  (int, int, int) dco_decode_record_u_32_casted_primitive_u_64_u_8(dynamic raw);

  @protected
  (int, ModulationLinkDto) dco_decode_record_u_32_modulation_link_dto(
    dynamic raw,
  );

  @protected
  (int, int, AutomationLaneDto) dco_decode_record_u_32_u_32_automation_lane_dto(
    dynamic raw,
  );

  @protected
  (int, UiBus) dco_decode_record_u_32_ui_bus(dynamic raw);

  @protected
  (int, UiGeneratorInstance) dco_decode_record_u_32_ui_generator_instance(
    dynamic raw,
  );

  @protected
  (int, UiMixerChannel) dco_decode_record_u_32_ui_mixer_channel(dynamic raw);

  @protected
  (int, UiPattern) dco_decode_record_u_32_ui_pattern(dynamic raw);

  @protected
  (int, UiTrack) dco_decode_record_u_32_ui_track(dynamic raw);

  @protected
  (int, int, int?)
  dco_decode_record_u_8_casted_primitive_u_64_opt_casted_primitive_u_64(
    dynamic raw,
  );

  @protected
  (int, int) dco_decode_record_u_8_u_8(dynamic raw);

  @protected
  (UiMixerChannel, List<UiEffectInstance>)
  dco_decode_record_ui_mixer_channel_list_ui_effect_instance(dynamic raw);

  @protected
  TailHandlingDTO dco_decode_tail_handling_dto(dynamic raw);

  @protected
  TrackAutomationTargetDto dco_decode_track_automation_target_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiApplicationState dco_decode_ui_application_state(dynamic raw);

  @protected
  UiAudioHardwareConfig dco_decode_ui_audio_hardware_config(dynamic raw);

  @protected
  UiBus dco_decode_ui_bus(dynamic raw);

  @protected
  UiClip dco_decode_ui_clip(dynamic raw);

  @protected
  UiClipSource dco_decode_ui_clip_source(dynamic raw);

  @protected
  UiClipboardContent dco_decode_ui_clipboard_content(dynamic raw);

  @protected
  UiEffectInstance dco_decode_ui_effect_instance(dynamic raw);

  @protected
  UiEffectParameterSnapshot dco_decode_ui_effect_parameter_snapshot(
    dynamic raw,
  );

  @protected
  UiEffectSummary dco_decode_ui_effect_summary(dynamic raw);

  @protected
  UiEffectTarget dco_decode_ui_effect_target(dynamic raw);

  @protected
  UiGeneratorInstance dco_decode_ui_generator_instance(dynamic raw);

  @protected
  UiGeneratorInstanceType dco_decode_ui_generator_instance_type(dynamic raw);

  @protected
  UiGeneratorParameterSnapshot dco_decode_ui_generator_parameter_snapshot(
    dynamic raw,
  );

  @protected
  UiMixerChannel dco_decode_ui_mixer_channel(dynamic raw);

  @protected
  UiMixerChannelParams dco_decode_ui_mixer_channel_params(dynamic raw);

  @protected
  UiMixerChannelSnapshot dco_decode_ui_mixer_channel_snapshot(dynamic raw);

  @protected
  UiMixerChannelTarget dco_decode_ui_mixer_channel_target(dynamic raw);

  @protected
  UiMixerState dco_decode_ui_mixer_state(dynamic raw);

  @protected
  UiNote dco_decode_ui_note(dynamic raw);

  @protected
  UiParamId dco_decode_ui_param_id(dynamic raw);

  @protected
  UiParameterType dco_decode_ui_parameter_type(dynamic raw);

  @protected
  UiParameterValue dco_decode_ui_parameter_value(dynamic raw);

  @protected
  UiPattern dco_decode_ui_pattern(dynamic raw);

  @protected
  UiPluginCommandResponse dco_decode_ui_plugin_command_response(dynamic raw);

  @protected
  UiPluginInfo dco_decode_ui_plugin_info(dynamic raw);

  @protected
  UiPluginInstance dco_decode_ui_plugin_instance(dynamic raw);

  @protected
  UiPluginParameter dco_decode_ui_plugin_parameter(dynamic raw);

  @protected
  UiPluginTarget dco_decode_ui_plugin_target(dynamic raw);

  @protected
  UiProjectMetadata dco_decode_ui_project_metadata(dynamic raw);

  @protected
  UiResizeEdge dco_decode_ui_resize_edge(dynamic raw);

  @protected
  UiRoutingConnection dco_decode_ui_routing_connection(dynamic raw);

  @protected
  UiRoutingNode dco_decode_ui_routing_node(dynamic raw);

  @protected
  UiSourceType dco_decode_ui_source_type(dynamic raw);

  @protected
  UiTrack dco_decode_ui_track(dynamic raw);

  @protected
  UiTrackType dco_decode_ui_track_type(dynamic raw);

  @protected
  UiTransportFeedback dco_decode_ui_transport_feedback(dynamic raw);

  @protected
  UiTransportState dco_decode_ui_transport_state(dynamic raw);

  @protected
  UiZeroCopyBufferResponse dco_decode_ui_zero_copy_buffer_response(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WavExportConfigDTO dco_decode_wav_export_config_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AudioWaveformUiForAudioProperties
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    SseDeserializer deserializer,
  );

  @protected
  BufferDataType
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
    SseDeserializer deserializer,
  );

  @protected
  PluginBufferHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    SseDeserializer deserializer,
  );

  @protected
  WaveformHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    SseDeserializer deserializer,
  );

  @protected
  ZeroCopyHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    SseDeserializer deserializer,
  );

  @protected
  AudioWaveformUiForAudioProperties
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    SseDeserializer deserializer,
  );

  @protected
  AudioWaveformUiForAudioProperties
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    SseDeserializer deserializer,
  );

  @protected
  PluginBufferHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    SseDeserializer deserializer,
  );

  @protected
  WaveformHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    SseDeserializer deserializer,
  );

  @protected
  ZeroCopyHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  Map<int, WaveformHandle>
  sse_decode_Map_u_32_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, AudioWaveformUiForSourceList>
  sse_decode_Map_u_32_audio_waveform_ui_for_source_list_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, AutomationLaneDto> sse_decode_Map_u_32_automation_lane_dto_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, ModulationLinkDto> sse_decode_Map_u_32_modulation_link_dto_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, UiBus> sse_decode_Map_u_32_ui_bus_None(SseDeserializer deserializer);

  @protected
  Map<int, UiGeneratorInstance> sse_decode_Map_u_32_ui_generator_instance_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, UiMixerChannel> sse_decode_Map_u_32_ui_mixer_channel_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, UiPattern> sse_decode_Map_u_32_ui_pattern_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, UiTrack> sse_decode_Map_u_32_ui_track_None(
    SseDeserializer deserializer,
  );

  @protected
  AudioWaveformUiForAudioProperties
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    SseDeserializer deserializer,
  );

  @protected
  BufferDataType
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
    SseDeserializer deserializer,
  );

  @protected
  PluginBufferHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    SseDeserializer deserializer,
  );

  @protected
  WaveformHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    SseDeserializer deserializer,
  );

  @protected
  ZeroCopyHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<double> sse_decode_StreamSink_f_32_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PerformanceMetricsDTO>
  sse_decode_StreamSink_performance_metrics_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<UiMixerChannelSnapshot>
  sse_decode_StreamSink_ui_mixer_channel_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<UiPluginCommandResponse>
  sse_decode_StreamSink_ui_plugin_command_response_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<UiTransportFeedback>
  sse_decode_StreamSink_ui_transport_feedback_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<UiZeroCopyBufferResponse>
  sse_decode_StreamSink_ui_zero_copy_buffer_response_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioExportConfigDTO sse_decode_audio_export_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  AudioWaveformUiForSourceList sse_decode_audio_waveform_ui_for_source_list(
    SseDeserializer deserializer,
  );

  @protected
  AutomationCurveTypeDto sse_decode_automation_curve_type_dto(
    SseDeserializer deserializer,
  );

  @protected
  AutomationLaneDto sse_decode_automation_lane_dto(
    SseDeserializer deserializer,
  );

  @protected
  AutomationPointDto sse_decode_automation_point_dto(
    SseDeserializer deserializer,
  );

  @protected
  AutomationTargetDto sse_decode_automation_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  BitDepthDTO sse_decode_bit_depth_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AudioWaveformUiForAudioProperties
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    SseDeserializer deserializer,
  );

  @protected
  WaveformHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    SseDeserializer deserializer,
  );

  @protected
  ZeroCopyHandle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    SseDeserializer deserializer,
  );

  @protected
  AudioExportConfigDTO sse_decode_box_autoadd_audio_export_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  AutomationLaneDto sse_decode_box_autoadd_automation_lane_dto(
    SseDeserializer deserializer,
  );

  @protected
  AutomationTargetDto sse_decode_box_autoadd_automation_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EffectAutomationTargetDto sse_decode_box_autoadd_effect_automation_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  MixerChannelParamTargetDto
  sse_decode_box_autoadd_mixer_channel_param_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  ModulationLinkDto sse_decode_box_autoadd_modulation_link_dto(
    SseDeserializer deserializer,
  );

  @protected
  ModulationSourceDto sse_decode_box_autoadd_modulation_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  Mp3ExportConfigDTO sse_decode_box_autoadd_mp_3_export_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackModeDto sse_decode_box_autoadd_playback_mode_dto(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_box_autoadd_record_u_8_u_8(
    SseDeserializer deserializer,
  );

  @protected
  TrackAutomationTargetDto sse_decode_box_autoadd_track_automation_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  UiEffectTarget sse_decode_box_autoadd_ui_effect_target(
    SseDeserializer deserializer,
  );

  @protected
  UiMixerChannel sse_decode_box_autoadd_ui_mixer_channel(
    SseDeserializer deserializer,
  );

  @protected
  UiMixerChannelParams sse_decode_box_autoadd_ui_mixer_channel_params(
    SseDeserializer deserializer,
  );

  @protected
  UiMixerChannelTarget sse_decode_box_autoadd_ui_mixer_channel_target(
    SseDeserializer deserializer,
  );

  @protected
  UiParamId sse_decode_box_autoadd_ui_param_id(SseDeserializer deserializer);

  @protected
  UiPluginInstance sse_decode_box_autoadd_ui_plugin_instance(
    SseDeserializer deserializer,
  );

  @protected
  UiPluginTarget sse_decode_box_autoadd_ui_plugin_target(
    SseDeserializer deserializer,
  );

  @protected
  UiRoutingConnection sse_decode_box_autoadd_ui_routing_connection(
    SseDeserializer deserializer,
  );

  @protected
  UiRoutingNode sse_decode_box_autoadd_ui_routing_node(
    SseDeserializer deserializer,
  );

  @protected
  WavExportConfigDTO sse_decode_box_autoadd_wav_export_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  EffectAutomationTargetDto sse_decode_effect_automation_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_8(SseDeserializer deserializer);

  @protected
  KarbeatPluginType sse_decode_karbeat_plugin_type(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AutomationPointDto> sse_decode_list_automation_point_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ParameterSpecDTO> sse_decode_list_parameter_spec_dto(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(int, AudioWaveformUiForSourceList)>
  sse_decode_list_record_u_32_audio_waveform_ui_for_source_list(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, WaveformHandle)>
  sse_decode_list_record_u_32_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_waveform_handle(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, AutomationLaneDto)>
  sse_decode_list_record_u_32_automation_lane_dto(SseDeserializer deserializer);

  @protected
  List<(int, int)> sse_decode_list_record_u_32_casted_primitive_u_64(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, int, int)> sse_decode_list_record_u_32_casted_primitive_u_64_u_8(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, ModulationLinkDto)>
  sse_decode_list_record_u_32_modulation_link_dto(SseDeserializer deserializer);

  @protected
  List<(int, int, AutomationLaneDto)>
  sse_decode_list_record_u_32_u_32_automation_lane_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, UiBus)> sse_decode_list_record_u_32_ui_bus(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, UiGeneratorInstance)>
  sse_decode_list_record_u_32_ui_generator_instance(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, UiMixerChannel)> sse_decode_list_record_u_32_ui_mixer_channel(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, UiPattern)> sse_decode_list_record_u_32_ui_pattern(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, UiTrack)> sse_decode_list_record_u_32_ui_track(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, int, int?)>
  sse_decode_list_record_u_8_casted_primitive_u_64_opt_casted_primitive_u_64(
    SseDeserializer deserializer,
  );

  @protected
  List<UiClip> sse_decode_list_ui_clip(SseDeserializer deserializer);

  @protected
  List<UiEffectInstance> sse_decode_list_ui_effect_instance(
    SseDeserializer deserializer,
  );

  @protected
  List<UiEffectParameterSnapshot> sse_decode_list_ui_effect_parameter_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<UiEffectSummary> sse_decode_list_ui_effect_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<UiGeneratorParameterSnapshot>
  sse_decode_list_ui_generator_parameter_snapshot(SseDeserializer deserializer);

  @protected
  List<UiNote> sse_decode_list_ui_note(SseDeserializer deserializer);

  @protected
  List<UiParameterValue> sse_decode_list_ui_parameter_value(
    SseDeserializer deserializer,
  );

  @protected
  List<UiPluginInfo> sse_decode_list_ui_plugin_info(
    SseDeserializer deserializer,
  );

  @protected
  List<UiPluginParameter> sse_decode_list_ui_plugin_parameter(
    SseDeserializer deserializer,
  );

  @protected
  List<UiRoutingConnection> sse_decode_list_ui_routing_connection(
    SseDeserializer deserializer,
  );

  @protected
  MixerChannelParamTargetDto sse_decode_mixer_channel_param_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  ModulationLinkDto sse_decode_modulation_link_dto(
    SseDeserializer deserializer,
  );

  @protected
  ModulationSourceDto sse_decode_modulation_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  Mp3ExportConfigDTO sse_decode_mp_3_export_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  Map<int, AudioWaveformUiForSourceList>?
  sse_decode_opt_Map_u_32_audio_waveform_ui_for_source_list_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AudioWaveformUiForAudioProperties?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    SseDeserializer deserializer,
  );

  @protected
  WaveformHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    SseDeserializer deserializer,
  );

  @protected
  ZeroCopyHandle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    SseDeserializer deserializer,
  );

  @protected
  AutomationLaneDto? sse_decode_opt_box_autoadd_automation_lane_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  ModulationLinkDto? sse_decode_opt_box_autoadd_modulation_link_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  List<ParameterSpecDTO>? sse_decode_opt_list_parameter_spec_dto(
    SseDeserializer deserializer,
  );

  @protected
  ParameterSpecDTO sse_decode_parameter_spec_dto(SseDeserializer deserializer);

  @protected
  ParameterValueTypeDTO sse_decode_parameter_value_type_dto(
    SseDeserializer deserializer,
  );

  @protected
  PerformanceMetricsDTO sse_decode_performance_metrics_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackModeDto sse_decode_playback_mode_dto(SseDeserializer deserializer);

  @protected
  (int, AudioWaveformUiForSourceList)
  sse_decode_record_u_32_audio_waveform_ui_for_source_list(
    SseDeserializer deserializer,
  );

  @protected
  (int, WaveformHandle)
  sse_decode_record_u_32_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_waveform_handle(
    SseDeserializer deserializer,
  );

  @protected
  (int, AutomationLaneDto) sse_decode_record_u_32_automation_lane_dto(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_u_32_casted_primitive_u_64(
    SseDeserializer deserializer,
  );

  @protected
  (int, int, int) sse_decode_record_u_32_casted_primitive_u_64_u_8(
    SseDeserializer deserializer,
  );

  @protected
  (int, ModulationLinkDto) sse_decode_record_u_32_modulation_link_dto(
    SseDeserializer deserializer,
  );

  @protected
  (int, int, AutomationLaneDto) sse_decode_record_u_32_u_32_automation_lane_dto(
    SseDeserializer deserializer,
  );

  @protected
  (int, UiBus) sse_decode_record_u_32_ui_bus(SseDeserializer deserializer);

  @protected
  (int, UiGeneratorInstance) sse_decode_record_u_32_ui_generator_instance(
    SseDeserializer deserializer,
  );

  @protected
  (int, UiMixerChannel) sse_decode_record_u_32_ui_mixer_channel(
    SseDeserializer deserializer,
  );

  @protected
  (int, UiPattern) sse_decode_record_u_32_ui_pattern(
    SseDeserializer deserializer,
  );

  @protected
  (int, UiTrack) sse_decode_record_u_32_ui_track(SseDeserializer deserializer);

  @protected
  (int, int, int?)
  sse_decode_record_u_8_casted_primitive_u_64_opt_casted_primitive_u_64(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_u_8_u_8(SseDeserializer deserializer);

  @protected
  (UiMixerChannel, List<UiEffectInstance>)
  sse_decode_record_ui_mixer_channel_list_ui_effect_instance(
    SseDeserializer deserializer,
  );

  @protected
  TailHandlingDTO sse_decode_tail_handling_dto(SseDeserializer deserializer);

  @protected
  TrackAutomationTargetDto sse_decode_track_automation_target_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiApplicationState sse_decode_ui_application_state(
    SseDeserializer deserializer,
  );

  @protected
  UiAudioHardwareConfig sse_decode_ui_audio_hardware_config(
    SseDeserializer deserializer,
  );

  @protected
  UiBus sse_decode_ui_bus(SseDeserializer deserializer);

  @protected
  UiClip sse_decode_ui_clip(SseDeserializer deserializer);

  @protected
  UiClipSource sse_decode_ui_clip_source(SseDeserializer deserializer);

  @protected
  UiClipboardContent sse_decode_ui_clipboard_content(
    SseDeserializer deserializer,
  );

  @protected
  UiEffectInstance sse_decode_ui_effect_instance(SseDeserializer deserializer);

  @protected
  UiEffectParameterSnapshot sse_decode_ui_effect_parameter_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  UiEffectSummary sse_decode_ui_effect_summary(SseDeserializer deserializer);

  @protected
  UiEffectTarget sse_decode_ui_effect_target(SseDeserializer deserializer);

  @protected
  UiGeneratorInstance sse_decode_ui_generator_instance(
    SseDeserializer deserializer,
  );

  @protected
  UiGeneratorInstanceType sse_decode_ui_generator_instance_type(
    SseDeserializer deserializer,
  );

  @protected
  UiGeneratorParameterSnapshot sse_decode_ui_generator_parameter_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  UiMixerChannel sse_decode_ui_mixer_channel(SseDeserializer deserializer);

  @protected
  UiMixerChannelParams sse_decode_ui_mixer_channel_params(
    SseDeserializer deserializer,
  );

  @protected
  UiMixerChannelSnapshot sse_decode_ui_mixer_channel_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  UiMixerChannelTarget sse_decode_ui_mixer_channel_target(
    SseDeserializer deserializer,
  );

  @protected
  UiMixerState sse_decode_ui_mixer_state(SseDeserializer deserializer);

  @protected
  UiNote sse_decode_ui_note(SseDeserializer deserializer);

  @protected
  UiParamId sse_decode_ui_param_id(SseDeserializer deserializer);

  @protected
  UiParameterType sse_decode_ui_parameter_type(SseDeserializer deserializer);

  @protected
  UiParameterValue sse_decode_ui_parameter_value(SseDeserializer deserializer);

  @protected
  UiPattern sse_decode_ui_pattern(SseDeserializer deserializer);

  @protected
  UiPluginCommandResponse sse_decode_ui_plugin_command_response(
    SseDeserializer deserializer,
  );

  @protected
  UiPluginInfo sse_decode_ui_plugin_info(SseDeserializer deserializer);

  @protected
  UiPluginInstance sse_decode_ui_plugin_instance(SseDeserializer deserializer);

  @protected
  UiPluginParameter sse_decode_ui_plugin_parameter(
    SseDeserializer deserializer,
  );

  @protected
  UiPluginTarget sse_decode_ui_plugin_target(SseDeserializer deserializer);

  @protected
  UiProjectMetadata sse_decode_ui_project_metadata(
    SseDeserializer deserializer,
  );

  @protected
  UiResizeEdge sse_decode_ui_resize_edge(SseDeserializer deserializer);

  @protected
  UiRoutingConnection sse_decode_ui_routing_connection(
    SseDeserializer deserializer,
  );

  @protected
  UiRoutingNode sse_decode_ui_routing_node(SseDeserializer deserializer);

  @protected
  UiSourceType sse_decode_ui_source_type(SseDeserializer deserializer);

  @protected
  UiTrack sse_decode_ui_track(SseDeserializer deserializer);

  @protected
  UiTrackType sse_decode_ui_track_type(SseDeserializer deserializer);

  @protected
  UiTransportFeedback sse_decode_ui_transport_feedback(
    SseDeserializer deserializer,
  );

  @protected
  UiTransportState sse_decode_ui_transport_state(SseDeserializer deserializer);

  @protected
  UiZeroCopyBufferResponse sse_decode_ui_zero_copy_buffer_response(
    SseDeserializer deserializer,
  );

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WavExportConfigDTO sse_decode_wav_export_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    AudioWaveformUiForAudioProperties self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
    BufferDataType self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    PluginBufferHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    WaveformHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    ZeroCopyHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    AudioWaveformUiForAudioProperties self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    AudioWaveformUiForAudioProperties self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    PluginBufferHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    WaveformHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    ZeroCopyHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer);

  @protected
  void
  sse_encode_Map_u_32_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle_None(
    Map<int, WaveformHandle> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_audio_waveform_ui_for_source_list_None(
    Map<int, AudioWaveformUiForSourceList> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_automation_lane_dto_None(
    Map<int, AutomationLaneDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_modulation_link_dto_None(
    Map<int, ModulationLinkDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_ui_bus_None(
    Map<int, UiBus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_ui_generator_instance_None(
    Map<int, UiGeneratorInstance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_ui_mixer_channel_None(
    Map<int, UiMixerChannel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_ui_pattern_None(
    Map<int, UiPattern> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_ui_track_None(
    Map<int, UiTrack> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    AudioWaveformUiForAudioProperties self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
    BufferDataType self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    PluginBufferHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    WaveformHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    ZeroCopyHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_f_32_Sse(
    RustStreamSink<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_performance_metrics_dto_Sse(
    RustStreamSink<PerformanceMetricsDTO> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ui_mixer_channel_snapshot_Sse(
    RustStreamSink<UiMixerChannelSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ui_plugin_command_response_Sse(
    RustStreamSink<UiPluginCommandResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ui_transport_feedback_Sse(
    RustStreamSink<UiTransportFeedback> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ui_zero_copy_buffer_response_Sse(
    RustStreamSink<UiZeroCopyBufferResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_export_config_dto(
    AudioExportConfigDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_waveform_ui_for_source_list(
    AudioWaveformUiForSourceList self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_automation_curve_type_dto(
    AutomationCurveTypeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_automation_lane_dto(
    AutomationLaneDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_automation_point_dto(
    AutomationPointDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_automation_target_dto(
    AutomationTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bit_depth_dto(BitDepthDTO self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    AudioWaveformUiForAudioProperties self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    WaveformHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    ZeroCopyHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_audio_export_config_dto(
    AudioExportConfigDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_automation_lane_dto(
    AutomationLaneDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_automation_target_dto(
    AutomationTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_effect_automation_target_dto(
    EffectAutomationTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mixer_channel_param_target_dto(
    MixerChannelParamTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_modulation_link_dto(
    ModulationLinkDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_modulation_source_dto(
    ModulationSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mp_3_export_config_dto(
    Mp3ExportConfigDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_playback_mode_dto(
    PlaybackModeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_u_8_u_8(
    (int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_automation_target_dto(
    TrackAutomationTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ui_effect_target(
    UiEffectTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_mixer_channel(
    UiMixerChannel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_mixer_channel_params(
    UiMixerChannelParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_mixer_channel_target(
    UiMixerChannelTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_param_id(
    UiParamId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_plugin_instance(
    UiPluginInstance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_plugin_target(
    UiPluginTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_routing_connection(
    UiRoutingConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_routing_node(
    UiRoutingNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wav_export_config_dto(
    WavExportConfigDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_effect_automation_target_dto(
    EffectAutomationTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_i_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_karbeat_plugin_type(
    KarbeatPluginType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_automation_point_dto(
    List<AutomationPointDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_parameter_spec_dto(
    List<ParameterSpecDTO> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_audio_waveform_ui_for_source_list(
    List<(int, AudioWaveformUiForSourceList)> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_record_u_32_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_waveform_handle(
    List<(int, WaveformHandle)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_automation_lane_dto(
    List<(int, AutomationLaneDto)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_casted_primitive_u_64(
    List<(int, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_casted_primitive_u_64_u_8(
    List<(int, int, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_modulation_link_dto(
    List<(int, ModulationLinkDto)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_u_32_automation_lane_dto(
    List<(int, int, AutomationLaneDto)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_ui_bus(
    List<(int, UiBus)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_ui_generator_instance(
    List<(int, UiGeneratorInstance)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_ui_mixer_channel(
    List<(int, UiMixerChannel)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_ui_pattern(
    List<(int, UiPattern)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_ui_track(
    List<(int, UiTrack)> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_record_u_8_casted_primitive_u_64_opt_casted_primitive_u_64(
    List<(int, int, int?)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_clip(List<UiClip> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ui_effect_instance(
    List<UiEffectInstance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_effect_parameter_snapshot(
    List<UiEffectParameterSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_effect_summary(
    List<UiEffectSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_generator_parameter_snapshot(
    List<UiGeneratorParameterSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_note(List<UiNote> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ui_parameter_value(
    List<UiParameterValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_plugin_info(
    List<UiPluginInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_plugin_parameter(
    List<UiPluginParameter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_routing_connection(
    List<UiRoutingConnection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mixer_channel_param_target_dto(
    MixerChannelParamTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_modulation_link_dto(
    ModulationLinkDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_modulation_source_dto(
    ModulationSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mp_3_export_config_dto(
    Mp3ExportConfigDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_u_32_audio_waveform_ui_for_source_list_None(
    Map<int, AudioWaveformUiForSourceList>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    AudioWaveformUiForAudioProperties? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    WaveformHandle? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    ZeroCopyHandle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_automation_lane_dto(
    AutomationLaneDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_modulation_link_dto(
    ModulationLinkDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_parameter_spec_dto(
    List<ParameterSpecDTO>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parameter_spec_dto(
    ParameterSpecDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parameter_value_type_dto(
    ParameterValueTypeDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_performance_metrics_dto(
    PerformanceMetricsDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_mode_dto(
    PlaybackModeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_audio_waveform_ui_for_source_list(
    (int, AudioWaveformUiForSourceList) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_record_u_32_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_waveform_handle(
    (int, WaveformHandle) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_automation_lane_dto(
    (int, AutomationLaneDto) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_casted_primitive_u_64(
    (int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_casted_primitive_u_64_u_8(
    (int, int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_modulation_link_dto(
    (int, ModulationLinkDto) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_u_32_automation_lane_dto(
    (int, int, AutomationLaneDto) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_ui_bus(
    (int, UiBus) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_ui_generator_instance(
    (int, UiGeneratorInstance) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_ui_mixer_channel(
    (int, UiMixerChannel) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_ui_pattern(
    (int, UiPattern) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_ui_track(
    (int, UiTrack) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_8_casted_primitive_u_64_opt_casted_primitive_u_64(
    (int, int, int?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_8_u_8((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_record_ui_mixer_channel_list_ui_effect_instance(
    (UiMixerChannel, List<UiEffectInstance>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tail_handling_dto(
    TailHandlingDTO self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_automation_target_dto(
    TrackAutomationTargetDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_application_state(
    UiApplicationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_audio_hardware_config(
    UiAudioHardwareConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_bus(UiBus self, SseSerializer serializer);

  @protected
  void sse_encode_ui_clip(UiClip self, SseSerializer serializer);

  @protected
  void sse_encode_ui_clip_source(UiClipSource self, SseSerializer serializer);

  @protected
  void sse_encode_ui_clipboard_content(
    UiClipboardContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_effect_instance(
    UiEffectInstance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_effect_parameter_snapshot(
    UiEffectParameterSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_effect_summary(
    UiEffectSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_effect_target(
    UiEffectTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_generator_instance(
    UiGeneratorInstance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_generator_instance_type(
    UiGeneratorInstanceType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_generator_parameter_snapshot(
    UiGeneratorParameterSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_mixer_channel(
    UiMixerChannel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_mixer_channel_params(
    UiMixerChannelParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_mixer_channel_snapshot(
    UiMixerChannelSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_mixer_channel_target(
    UiMixerChannelTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_mixer_state(UiMixerState self, SseSerializer serializer);

  @protected
  void sse_encode_ui_note(UiNote self, SseSerializer serializer);

  @protected
  void sse_encode_ui_param_id(UiParamId self, SseSerializer serializer);

  @protected
  void sse_encode_ui_parameter_type(
    UiParameterType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_parameter_value(
    UiParameterValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_pattern(UiPattern self, SseSerializer serializer);

  @protected
  void sse_encode_ui_plugin_command_response(
    UiPluginCommandResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_plugin_info(UiPluginInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ui_plugin_instance(
    UiPluginInstance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_plugin_parameter(
    UiPluginParameter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_plugin_target(
    UiPluginTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_project_metadata(
    UiProjectMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_resize_edge(UiResizeEdge self, SseSerializer serializer);

  @protected
  void sse_encode_ui_routing_connection(
    UiRoutingConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_routing_node(UiRoutingNode self, SseSerializer serializer);

  @protected
  void sse_encode_ui_source_type(UiSourceType self, SseSerializer serializer);

  @protected
  void sse_encode_ui_track(UiTrack self, SseSerializer serializer);

  @protected
  void sse_encode_ui_track_type(UiTrackType self, SseSerializer serializer);

  @protected
  void sse_encode_ui_transport_feedback(
    UiTransportFeedback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_transport_state(
    UiTransportState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_zero_copy_buffer_response(
    UiZeroCopyBufferResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wav_export_config_dto(
    WavExportConfigDTO self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioPropertiesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioPropertiesPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioPropertiesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioProperties =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioWaveformUiForAudioPropertiesPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataTypePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataTypePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataTypePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataType =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBufferDataTypePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginBufferHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWaveformHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_karbeat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZeroCopyHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
