[package]
name = "karbeat_flutter_ffi"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
karbeat-core.workspace = true
karbeat-plugin-api.workspace = true
karbeat-utils.workspace = true

anyhow.workspace = true
env_logger.workspace = true
flutter_rust_bridge.workspace = true
log.workspace = true
serde.workspace = true
thiserror.workspace = true
rtrb.workspace = true
triple_buffer.workspace = true
karbeat-plugins.workspace = true
smallvec.workspace = true
memmap2.workspace = true
bytemuck.workspace = true
chrono.workspace = true
serde_json.workspace = true
parking_lot.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
