[package]
name = "karbeat_flutter_ffi"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-only"

[lib]
name = "karbeat_flutter_ffi"
crate-type = ["cdylib", "staticlib"]


[dependencies]
karbeat-vst3.workspace = true
karbeat-clap.workspace = true
karbeat-lv2.workspace = true
karbeat-host.workspace = true
karbeat-plugin-api.workspace = true
karbeat-utils.workspace = true

anyhow.workspace = true
env_logger.workspace = true
flutter_rust_bridge = "=2.12.0"
log.workspace = true
serde.workspace = true
thiserror.workspace = true
rtrb.workspace = true

karbeat-plugins.workspace = true
smallvec.workspace = true
memmap2.workspace = true
bytemuck.workspace = true
chrono.workspace = true
cpal.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
once_cell.workspace = true
ndk-context = { version = "0.1.1" }
jni = { version = "0.22.4" }

[target.'cfg(target_os = "windows")'.dependencies]
karbeat-core = { workspace = true, features = ["asio"] }
karbeat-host-api.workspace = true

[target.'cfg(not(target_os = "windows"))'.dependencies]
karbeat-core.workspace = true

[dev-dependencies]
shuttle.workspace = true

[lints]
workspace = true
