import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:karbeat/app/providers/project_provider.dart';
import 'package:karbeat/core/utils/logger.dart';
import 'package:karbeat/features/plugins/abstract_plugin_screen.dart';
import 'package:karbeat/features/piano_roll/view/scrollable_virtual_keyboard.dart';
import 'package:karbeat/src/rust/api/audio.dart' as audio_api;
import 'package:karbeat/src/rust/api/plugin.dart' as plugin_api;

/// Generic Dynamic Plugin Screen that generates UI from plugin parameter specs.
/// This acts as a fallback for ANY plugin (Generators or Effects) that does not have custom UI.
class DynamicPluginScreen extends AbstractPluginScreen {
  final String _pluginName;

  const DynamicPluginScreen({
    super.key,
    required super.target,
    required String pluginName,
  }) : _pluginName = pluginName;

  @override
  ConsumerState<DynamicPluginScreen> createState() =>
      _DynamicPluginScreenState();
}

class _DynamicPluginScreenState
    extends AbstractPluginScreenState<DynamicPluginScreen> {
  // Track active notes for keyboard visualization
  final Set<int> _activeNotes = {};

  @override
  String get pluginName => widget._pluginName;

  /// Helper to check if the current target is a Generator.
  /// (Uses Freezed's union mapping generated by FRB).
  bool get _isGenerator =>
      widget.target.whenOrNull(generator: (_) => true) ?? false;

  @override
  Widget buildPluginBody(BuildContext context) {
    return Column(
      children: [
        // Render the dynamic parameters (inherited from AbstractPluginScreenState)
        Expanded(child: super.buildDynamicPluginBody(context)),

        // Render the Scrollable MIDI Keyboard ONLY if this plugin is a Generator
        if (_isGenerator)
          ScrollableVirtualKeyboard(
            height: 120,
            onNoteOn: _handleNoteOn,
            onNoteOff: _handleNoteOff,
            activeNotes: _activeNotes,
            initialCenterNote: 72,
          ),
      ],
    );
  }

  void _handleNoteOn(int note) async {
    if (!_isGenerator) return;

    setState(() => _activeNotes.add(note));
    try {
      final ctx = ref.read(projectProvider.notifier).dawContext;
      final generatorId = widget.target.when(
        generator: (id) => id,
        trackEffect: (int trackId, int effectId) {
          throw Exception('Invalid target type for generator');
        },
        busEffect: (int busId, int effectId) {
          throw Exception('Invalid target type for generator');
        },
        masterEffect: (int field0) {
          throw Exception('Invalid target type for generator');
        },
      );
      // We pass widget.pluginId because the instance ID is the generator ID
      await audio_api.playPreviewNoteGenerator(
        ctx: ctx,
        generatorId: generatorId,
        noteKey: note,
        velocity: 100,
        isOn: true,
      );
    } catch (e) {
      AppLogger.error('Error playing note on: $e');
    }
  }

  void _handleNoteOff(int note) async {
    if (!_isGenerator) return;

    setState(() => _activeNotes.remove(note));
    try {
      final ctx = ref.read(projectProvider.notifier).dawContext;
      final generatorId = widget.target.when(
        generator: (id) => id,
        trackEffect: (int trackId, int effectId) {
          throw Exception('Invalid target type for generator');
        },
        busEffect: (int busId, int effectId) {
          throw Exception('Invalid target type for generator');
        },
        masterEffect: (int field0) {
          throw Exception('Invalid target type for generator');
        },
      );
      await audio_api.playPreviewNoteGenerator(
        ctx: ctx,
        generatorId: generatorId,
        noteKey: note,
        velocity: 100,
        isOn: false,
      );
    } catch (e) {
      AppLogger.error('Error playing note off: $e');
    }
  }
}
