[package]
name = "karbeat-plugin-api"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Plugin API for Karbeat"

[dependencies]
karbeat-dsp.workspace = true
karbeat-utils.workspace = true
karbeat-macros.workspace = true

anyhow.workspace = true
serde.workspace = true
log.workspace = true
indexmap.workspace = true
smallvec.workspace = true
serde_json.workspace = true
heck.workspace = true
karbeat-plugin-types.workspace = true
hashbrown.workspace = true
rmp-serde.workspace = true
parking_lot.workspace = true
dyn-clone.workspace = true
raw-window-handle.workspace = true

[lints]
workspace = true
