[workspace]
resolver = "2"
members = [
    "karbeat-core",
    "karbeat-dsp",
    "karbeat-host",
    "karbeat-flutter-ffi",
    "karbeat-plugins",
    "karbeat-plugin-api",
    "karbeat-utils",
    "karbeat-macros",
    "karbeat-plugin-types",
]

[workspace.dependencies]
karbeat-core = { path = "karbeat-core" }
karbeat-dsp = { path = "karbeat-dsp" }
karbeat_flutter_ffi = { path = "karbeat-flutter-ffi" }
karbeat-host = { path = "karbeat-host" }
karbeat-plugin-api = { path = "karbeat-plugin-api" }
karbeat-plugins = { path = "karbeat-plugins" }
karbeat-utils = { path = "karbeat-utils" }
karbeat-macros = { path = "karbeat-macros" }
karbeat-plugin-types = { path = "karbeat-plugin-types" }
anyhow = "1.0.103"
cpal = { version = "0.17.3"}
env_logger = "0.11"
fastrand = "2.4"
flutter_rust_bridge = "=2.11.1"
log = "0.4.28"
minimp3 = "0.6.1"
once_cell = "1.21"
rodio = "0.22.1"
rtrb = "0.3.2"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.149"
symphonia = { version = "0.5.5", default-features = false, features = [
    "aac",
    "mp3",
    "flac",
    "wav",
    "ogg",
] }
triple_buffer = "9.0.0"
rustfft = "6.4.1"
thiserror = "2.0"
dasp = { version = "0.11.0", features = ["all"] }
smallvec = { version = "1.15.1", features = ["serde"] }
hashbrown = { version = "0.17.0", features = ["serde"] }
indexmap = { version = "2.14.0", features = ["serde"] }
itertools = { version = "^0.14" }
num-complex = "0.4.6"
parking_lot = "0.12.5"
uuid = { version = "1.22.0", features = ["v4", "serde"] }
memmap2 = "0.9.11"
bytemuck = "1.25.0"
tempfile = "3.27.0"
zip = "8.5"
toml = "1.1.2"
chrono = { version = "0.4.44", features = ["serde"] }
rmp-serde = "1.3.1"
derive_builder = "0.20.2"
hound = "3.5.1"
strum = { version = "0.28.0", features = ["derive"] }
num-traits = "0.2"
wide = "1.6.0"
heck = "0.5.0"
fundsp = "0.23.0"
rand = "0.10.1"
vcpkg = "0.2.15"
bindgen = "0.72.1"
pkg-config = "0.3.33"
rubato = "4.0.0"

[profile.dev]
opt-level = 3
debug = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]

codegen-units = 1
lto = true
opt-level = 3

[workspace.lints.rust]
unused = "warn"

[workspace.lints.clippy]
all = { level = "allow", priority = -2 }
correctness = { level = "deny", priority = -1 }
perf = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
# type_complexity = "allow"
