[workspace]
resolver = "2"
members = [
    "karbeat-core",
    "karbeat-dsp",
    "karbeat-host",
    "karbeat-flutter-ffi",
    "karbeat-plugins",
    "karbeat-plugin-api",
    "karbeat-utils",
    "karbeat-macros",
    "karbeat-plugin-types", "karbeat-vst3", "karbeat-clap",
]

[workspace.package]
version = "0.3.0"
edition = "2024"
license = "GPL 3.0"

[workspace.dependencies]
karbeat-core = { path = "karbeat-core" }
karbeat-dsp = { path = "karbeat-dsp" }
karbeat_flutter_ffi = { path = "karbeat-flutter-ffi" }
karbeat-host = { path = "karbeat-host" }
karbeat-plugin-api = { path = "karbeat-plugin-api" }
karbeat-plugins = { path = "karbeat-plugins" }
karbeat-utils = { path = "karbeat-utils" }
karbeat-macros = { path = "karbeat-macros" }
karbeat-plugin-types = { path = "karbeat-plugin-types" }
anyhow = "1.0.103"
cpal = { version = "0.17.3"}
env_logger = "0.11"
fastrand = "2.4"
flutter_rust_bridge = "=2.11.1"
log = "0.4.28"
minimp3 = "0.6.1"
once_cell = "1.21"
rodio = {version= "0.22.1", features=["symphonia-all"]}
rtrb = "0.3.2"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.149"
triple_buffer = "9.0.0"
rustfft = "6.4.1"
thiserror = "2.0"
dasp = { version = "0.11.0", features = ["all"] }
smallvec = { version = "1.15.1", features = ["serde"] }
hashbrown = { version = "0.17.0", features = ["serde"] }
indexmap = { version = "2.14.0", features = ["serde"] }
itertools = { version = "^0.14" }
num-complex = "0.4.6"
parking_lot = "0.12.5"
uuid = { version = "1.22.0", features = ["v4", "serde"] }
memmap2 = "0.9.11"
bytemuck = "1.25.0"
tempfile = "3.27.0"
zip = "8.5"
toml = "1.1.4"
chrono = { version = "0.4.44", features = ["serde"] }
rmp-serde = "1.3.1"
derive_builder = "0.20.2"
hound = "3.5.1"
strum = { version = "0.28.0", features = ["derive"] }
num-traits = "0.2"
wide = "1.6.0"
heck = "0.5.0"
fundsp = "0.23.0"
rand = "0.10.1"
vcpkg = "0.2.15"
bindgen = "0.72.1"
pkg-config = "0.3.33"
rubato = "4.0.0"
dyn-clone = "1.0.20"
raw-window-handle = "0.6.2"
slotmap = {version = "1.1.1", features=["serde"] }
slab = {version = "0.4.12", features=["serde"]}

[profile.dev]
opt-level = 3
debug = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]

codegen-units = 1
lto = true
opt-level = 3

[workspace.lints.rust]
unused = { level = "warn", priority = -1 }
unused_must_use = "deny"
unknown_lints = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[workspace.lints.clippy]
all = { level = "warn", priority = -3 }
pedantic = { level = "warn", priority = -3 }
cargo = { level = "warn", priority = -3 }

correctness = { level = "deny", priority = -2 }
suspicious = { level = "deny", priority = -2 }

unwrap_used = "deny"
expect_used = "deny"

panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"

dbg_macro = "deny"

as_conversions = "deny"

undocumented_unsafe_blocks = "deny"
multiple_unsafe_ops_per_block = "deny"
macro_metavars_in_unsafe = "deny"
missing_safety_doc = "deny"

let_underscore_must_use = "deny"

await_holding_lock = "deny"
await_holding_refcell_ref = "deny"

exit = "deny"

indexing_slicing = "warn"
string_slice = "warn"
arithmetic_side_effects = "warn"

allow_attributes_without_reason = "deny"

wildcard_dependencies = "deny"

multiple_crate_versions = "allow"
cargo_common_metadata = "allow"

module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
similar_names = "allow"
struct_excessive_bools = "allow"
