//! The application's desktop identity, shared by editor windows so desktops group them with
//! the main window and show the application icon.
//!
//! The icon blobs are generated by `scripts/generate_icons.sh` from `assets/icon/app_icon.svg`.

use std::sync::OnceLock;

/// Application ID: the Wayland `app_id`, and the desktop-entry name and X11 `WM_CLASS` the
/// main window uses.
pub const APP_ID: &str = "app.digidaw.Digidaw";

/// X11 `WM_CLASS` value: instance and class name, each NUL-terminated.
pub const WM_CLASS: &[u8] = b"app.digidaw.Digidaw\0app.digidaw.Digidaw\0";

/// Window icons as `(size, little-endian BGRA rows)`.
const ICONS: [(u32, &[u8]); 2] = [
    (
        32,
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/assets/window_icon_32.bgra"
        )),
    ),
    (
        64,
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/assets/window_icon_64.bgra"
        )),
    ),
];

/// `_NET_WM_ICON` value: for each size, its width and height, then one non-premultiplied
/// ARGB pixel per element, row by row. Built once.
pub fn net_wm_icon() -> &'static [u32] {
    static ICON: OnceLock<Vec<u32>> = OnceLock::new();
    ICON.get_or_init(|| {
        let mut data = Vec::new();
        for (size, bgra) in ICONS {
            data.extend([size, size]);
            // Little-endian B, G, R, A bytes read as one u32 are exactly 0xAARRGGBB.
            let (pixels, _) = bgra.as_chunks::<4>();
            data.extend(pixels.iter().map(|pixel| u32::from_le_bytes(*pixel)));
        }
        data
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wm_class_names_the_app_id_twice() {
        let expected = format!("{APP_ID}\0{APP_ID}\0");
        assert_eq!(WM_CLASS, expected.as_bytes());
    }

    #[test]
    fn icon_holds_both_sizes_with_an_opaque_centre() {
        let icon = net_wm_icon();
        assert_eq!(icon.len(), 2 + 32 * 32 + 2 + 64 * 64);
        assert_eq!(icon.get(..2), Some(&[32, 32][..]));
        let large = icon.get(2 + 32 * 32..).unwrap_or_default();
        assert_eq!(large.get(..2), Some(&[64, 64][..]));
        let centre = large.get(2 + 32 * 64 + 32).copied().unwrap_or_default();
        assert_eq!(centre >> 24, 0xff, "centre pixel {centre:#010x}");
    }
}
