// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../plugin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Compute the magnitude response curve for a parametric EQ effect on a track.
///
/// Creates a temporary plugin instance, applies stored parameters, and evaluates
/// the exact biquad transfer function at log-spaced frequency points.
Future<List<UiResponseCurvePoint>> getEqResponseCurve({
  required UiEffectTarget target,
  required int effectId,
  required int numPoints,
}) => RustLib.instance.api.crateApiPluginsEqGetEqResponseCurve(
  target: target,
  effectId: effectId,
  numPoints: numPoints,
);

List<UiResponseCurvePoint> parseEqCurveResponse({required String jsonStr}) =>
    RustLib.instance.api.crateApiPluginsEqParseEqCurveResponse(
      jsonStr: jsonStr,
    );

/// A point on the EQ response curve (DTO for FRB)
class UiResponseCurvePoint {
  final double frequency;
  final double magnitudeDb;

  const UiResponseCurvePoint({
    required this.frequency,
    required this.magnitudeDb,
  });

  @override
  int get hashCode => frequency.hashCode ^ magnitudeDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiResponseCurvePoint &&
          runtimeType == other.runtimeType &&
          frequency == other.frequency &&
          magnitudeDb == other.magnitudeDb;
}
