// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZeroCopyHandle>>
abstract class ZeroCopyHandle implements RustOpaqueInterface {
  /// Tells Dart what kind of TypedList to create
  BufferDataTypeDto dataType();

  /// Gets the number of elements
  int lengthElements();

  /// Gets the raw memory address
  int memoryAddress();
}
