// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BufferDataType>>
abstract class BufferDataType implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZeroCopyHandle>>
abstract class ZeroCopyHandle implements RustOpaqueInterface {
  /// Tells Dart what kind of TypedList to create
  BufferDataType dataType();

  /// Gets the number of elements (NOT bytes, making Dart's job easier)
  int lengthElements();

  /// Gets the raw memory address
  int memoryAddress();
}
