// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'opaque.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`

enum BufferDataTypeDto {
  float32,
  uint8,
  int32,
  int8;

  Future<String> dataTypeStr() => RustLib.instance.api
      .crateApiPluginsTypesBufferDataTypeDtoDataTypeStr(that: this);
}

class PluginTelemetrySnapshotDto {
  final List<(int, double)> parameters;
  final Map<String, ZeroCopyHandle> bufferHandles;

  const PluginTelemetrySnapshotDto({
    required this.parameters,
    required this.bufferHandles,
  });

  @override
  int get hashCode => parameters.hashCode ^ bufferHandles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginTelemetrySnapshotDto &&
          runtimeType == other.runtimeType &&
          parameters == other.parameters &&
          bufferHandles == other.bufferHandles;
}
