[package]
name = "karbeat-host"
version.workspace = true
edition.workspace = true
license = "Apache-2.0 OR MIT"
description = "3rd-party plugin hosting implementation for Karbeat, including VST3, LV2, and CLAP support"

[dependencies]
karbeat-plugin-api.workspace = true
log.workspace = true
serde_json.workspace = true
hashbrown.workspace = true
raw-window-handle.workspace = true
serde.workspace = true
thiserror.workspace = true
rtrb.workspace = true
tempfile.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
glib.workspace = true
x11rb.workspace = true
wayland-client.workspace = true
smithay-client-toolkit.workspace = true

[lints]
workspace = true
