// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'project.dart';
part 'audio_analysis.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `render`, `schedule_render`, `schedule_source_renders`, `source_spec`, `started`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Sets the Beat This! model files, the mel front end and the small beat model; call once
/// at startup with the bundled asset paths.
Future<void> configureTempoModels({
  required String melPath,
  required String beatPath,
}) => RustLib.instance.api.crateApiAudioAnalysisConfigureTempoModels(
  melPath: melPath,
  beatPath: beatPath,
);

/// Detects the tempo, beats and downbeats of an audio source in the background.
///
/// Stores them on the source as one undoable step. Returns the job id.
Future<int> startTempoDetection({
  required DawContext ctx,
  required int sourceId,
}) => RustLib.instance.api.crateApiAudioAnalysisStartTempoDetection(
  ctx: ctx,
  sourceId: sourceId,
);

/// Stretches an audio source to the project tempo in the background, keeping its pitch.
///
/// `warp` stretches beat by beat so every detected beat lands on the grid; it needs a
/// finished tempo detection. The source switches to stretch mode and follows later tempo
/// changes. Undoable. Returns the job id.
Future<int> startFitToTempo({
  required DawContext ctx,
  required int sourceId,
  required bool warp,
}) => RustLib.instance.api.crateApiAudioAnalysisStartFitToTempo(
  ctx: ctx,
  sourceId: sourceId,
  warp: warp,
);

/// Changes how an audio source follows the project tempo (undoable), then renders it in the
/// background when needed. Stretch keeps the pitch; Resampled bends it like tape.
Future<void> setAudioSourceSampleMode({
  required DawContext ctx,
  required int sourceId,
  required UiAudioSampleMode mode,
}) => RustLib.instance.api.crateApiAudioAnalysisSetAudioSourceSampleMode(
  ctx: ctx,
  sourceId: sourceId,
  mode: mode,
);

/// Sets an audio source's pitch shift in semitones (clamped to two octaves either way) and
/// whether to preserve formants (undoable), then renders it in the background. The original
/// audio plays until the render is ready.
Future<void> setWaveformPitch({
  required DawContext ctx,
  required int sourceId,
  required double pitchSemitones,
  required bool preserveFormants,
}) => RustLib.instance.api.crateApiAudioAnalysisSetWaveformPitch(
  ctx: ctx,
  sourceId: sourceId,
  pitchSemitones: pitchSemitones,
  preserveFormants: preserveFormants,
);

/// Sets an audio source's normalize, invert and reverse edits (undoable), then renders them
/// in the background. The original audio plays until the render is ready.
Future<void> setWaveformEdits({
  required DawContext ctx,
  required int sourceId,
  required bool normalize,
  required bool invert,
  required bool reverse,
}) => RustLib.instance.api.crateApiAudioAnalysisSetWaveformEdits(
  ctx: ctx,
  sourceId: sourceId,
  normalize: normalize,
  invert: invert,
  reverse: reverse,
);

/// Tempo detected in an audio source.
@freezed
sealed class UiBeatGrid with _$UiBeatGrid {
  const factory UiBeatGrid({
    required double bpm,
    required double confidence,
    required Float32List beats,
    required Float32List downbeats,
  }) = _UiBeatGrid;
}
