// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'project.dart';
part 'audio_settings.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `cpal_default_host_name`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

Future<List<UiAudioHostInfo>> listOutputHosts() =>
    RustLib.instance.api.crateApiAudioSettingsListOutputHosts();

Future<List<UiOutputDeviceInfo>> listOutputDevices({String? hostName}) =>
    RustLib.instance.api.crateApiAudioSettingsListOutputDevices(
      hostName: hostName,
    );

Future<UiAudioRuntimeSettings> getAudioRuntimeSettings({
  required DawContext ctx,
}) =>
    RustLib.instance.api.crateApiAudioSettingsGetAudioRuntimeSettings(ctx: ctx);

Future<int> getOutputUnderrunSamples() =>
    RustLib.instance.api.crateApiAudioSettingsGetOutputUnderrunSamples();

Future<UiAudioRuntimeSettings> setOutputSelection({
  required DawContext ctx,
  String? hostName,
  String? deviceId,
}) => RustLib.instance.api.crateApiAudioSettingsSetOutputSelection(
  ctx: ctx,
  hostName: hostName,
  deviceId: deviceId,
);

Future<UiAudioRuntimeSettings> setDspConfig({
  required DawContext ctx,
  required int sampleRate,
  required int blockSize,
}) => RustLib.instance.api.crateApiAudioSettingsSetDspConfig(
  ctx: ctx,
  sampleRate: sampleRate,
  blockSize: blockSize,
);

Future<Uint32List> supportedDspSampleRates() =>
    RustLib.instance.api.crateApiAudioSettingsSupportedDspSampleRates();

Future<Uint32List> supportedDspBlockSizes() =>
    RustLib.instance.api.crateApiAudioSettingsSupportedDspBlockSizes();

@freezed
sealed class UiActualDeviceStreamConfig with _$UiActualDeviceStreamConfig {
  const factory UiActualDeviceStreamConfig({
    required String hostName,
    required String deviceId,
    required String deviceName,
    required int sampleRate,
    required int callbackBufferSize,
    required int channels,
  }) = _UiActualDeviceStreamConfig;
}

@freezed
sealed class UiAudioHostInfo with _$UiAudioHostInfo {
  const factory UiAudioHostInfo({
    String? hostName,
    required String displayName,
  }) = _UiAudioHostInfo;
}

@freezed
sealed class UiAudioRuntimeSettings with _$UiAudioRuntimeSettings {
  const factory UiAudioRuntimeSettings({
    required UiRequestedOutputConfig requestedOutput,
    required UiRequestedDspConfig requestedDsp,
    UiActualDeviceStreamConfig? actualStream,
    required UiDeviceStreamStatus streamStatus,
  }) = _UiAudioRuntimeSettings;
}

@freezed
sealed class UiDeviceStreamStatus with _$UiDeviceStreamStatus {
  const UiDeviceStreamStatus._();

  const factory UiDeviceStreamStatus.starting() = UiDeviceStreamStatus_Starting;
  const factory UiDeviceStreamStatus.running() = UiDeviceStreamStatus_Running;
  const factory UiDeviceStreamStatus.retrying({required String reason}) =
      UiDeviceStreamStatus_Retrying;
  const factory UiDeviceStreamStatus.unavailable({required String reason}) =
      UiDeviceStreamStatus_Unavailable;
}

@freezed
sealed class UiOutputDeviceInfo with _$UiOutputDeviceInfo {
  const factory UiOutputDeviceInfo({
    String? deviceId,
    required String displayName,
    required bool isCurrentSystemDefault,
  }) = _UiOutputDeviceInfo;
}

@freezed
sealed class UiOutputDeviceSelection with _$UiOutputDeviceSelection {
  const UiOutputDeviceSelection._();

  const factory UiOutputDeviceSelection.systemDefault() =
      UiOutputDeviceSelection_SystemDefault;
  const factory UiOutputDeviceSelection.specific({
    required String id,
    required String name,
  }) = UiOutputDeviceSelection_Specific;
}

@freezed
sealed class UiOutputHostSelection with _$UiOutputHostSelection {
  const UiOutputHostSelection._();

  const factory UiOutputHostSelection.systemDefault() =
      UiOutputHostSelection_SystemDefault;
  const factory UiOutputHostSelection.named({required String name}) =
      UiOutputHostSelection_Named;
}

@freezed
sealed class UiRequestedDspConfig with _$UiRequestedDspConfig {
  const factory UiRequestedDspConfig({
    required int sampleRate,
    required int blockSize,
  }) = _UiRequestedDspConfig;
}

@freezed
sealed class UiRequestedOutputConfig with _$UiRequestedOutputConfig {
  const factory UiRequestedOutputConfig({
    required UiOutputHostSelection host,
    required UiOutputDeviceSelection device,
  }) = _UiRequestedOutputConfig;
}
