// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'project.dart';
part 'audio.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// GETTER: Fetch details + Downsampled Buffer for UI
Future<AudioWaveformUiForAudioProperties?> getAudioProperties({
  required int id,
}) => RustLib.instance.api.crateApiAudioGetAudioProperties(id: id);

/// ACTION: Play the sound via the Engine
Future<void> playSourcePreview({required int id}) =>
    RustLib.instance.api.crateApiAudioPlaySourcePreview(id: id);

Future<void> stopAllPreviews() =>
    RustLib.instance.api.crateApiAudioStopAllPreviews();

Future<UiAudioHardwareConfig> getAudioConfig() =>
    RustLib.instance.api.crateApiAudioGetAudioConfig();

Stream<UiTransportFeedback> createPositionStream() =>
    RustLib.instance.api.crateApiAudioCreatePositionStream();

/// play preview sound when drawing note or pressing the piano tile on the UI
Future<void> playPreviewNote({
  required int trackId,
  required int noteKey,
  required int velocity,
  required bool isOn,
}) => RustLib.instance.api.crateApiAudioPlayPreviewNote(
  trackId: trackId,
  noteKey: noteKey,
  velocity: velocity,
  isOn: isOn,
);

/// Play preview sound directly on a generator (without requiring a track).
/// Used in plugin editor screens to test synth sounds.
Future<void> playPreviewNoteGenerator({
  required int generatorId,
  required int noteKey,
  required int velocity,
  required bool isOn,
}) => RustLib.instance.api.crateApiAudioPlayPreviewNoteGenerator(
  generatorId: generatorId,
  noteKey: noteKey,
  velocity: velocity,
  isOn: isOn,
);

void setMetronomeActive({required bool active}) =>
    RustLib.instance.api.crateApiAudioSetMetronomeActive(active: active);

@freezed
sealed class UiTransportFeedback with _$UiTransportFeedback {
  const factory UiTransportFeedback({
    required int samples,
    required int ticks,
    required int beat,
    required int bar,
    required double tempo,
    required int sampleRate,
    required bool isPlaying,
    required bool isLooping,
    required bool isRecording,
    required bool isPatternPlaying,
    required bool isPatternMode,
    required int patternSamples,
    required int patternTicks,
    required int patternBeat,
    required int patternBar,
  }) = _UiTransportFeedback;
}
