// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'automation.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Fetch the list of (modulation_id, automation_id, automation_lane) where
/// the target is the given track id
Future<List<(int, int, AutomationLaneDto)>> getAutomationLanesForTrack({
  required int trackId,
}) => RustLib.instance.api.crateApiAutomationGetAutomationLanesForTrack(
  trackId: trackId,
);

/// Fetch the list of (modulation_id, automation_id, automation_lane) where
/// the target is the given bus id
Future<List<(int, int, AutomationLaneDto)>> getAutomationLanesForBus({
  required int busId,
}) => RustLib.instance.api.crateApiAutomationGetAutomationLanesForBus(
  busId: busId,
);

Future<AutomationLaneDto> addAutomationLane({
  required AutomationTargetDto target,
  required String label,
  required double min,
  required double max,
  required double defaultValue,
}) => RustLib.instance.api.crateApiAutomationAddAutomationLane(
  target: target,
  label: label,
  min: min,
  max: max,
  defaultValue: defaultValue,
);

enum AutomationCurveTypeDto { linear, exponential, step }

class AutomationLaneDto {
  final int id;
  final String label;
  final List<AutomationPointDto> points;
  final bool enabled;
  final double min;
  final double max;
  final double defaultValue;

  const AutomationLaneDto({
    required this.id,
    required this.label,
    required this.points,
    required this.enabled,
    required this.min,
    required this.max,
    required this.defaultValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      points.hashCode ^
      enabled.hashCode ^
      min.hashCode ^
      max.hashCode ^
      defaultValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutomationLaneDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          points == other.points &&
          enabled == other.enabled &&
          min == other.min &&
          max == other.max &&
          defaultValue == other.defaultValue;
}

class AutomationPointDto {
  final int timeTicks;
  final double value;
  final AutomationCurveTypeDto curveType;
  final double tension;

  const AutomationPointDto({
    required this.timeTicks,
    required this.value,
    required this.curveType,
    required this.tension,
  });

  @override
  int get hashCode =>
      timeTicks.hashCode ^
      value.hashCode ^
      curveType.hashCode ^
      tension.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutomationPointDto &&
          runtimeType == other.runtimeType &&
          timeTicks == other.timeTicks &&
          value == other.value &&
          curveType == other.curveType &&
          tension == other.tension;
}

@freezed
sealed class AutomationTargetDto with _$AutomationTargetDto {
  const AutomationTargetDto._();

  const factory AutomationTargetDto.trackGeneratorPluginParam({
    required int trackId,
    required int paramId,
  }) = AutomationTargetDto_TrackGeneratorPluginParam;
  const factory AutomationTargetDto.track({
    required int trackId,
    required MixerChannelTargetDto mixTarget,
  }) = AutomationTargetDto_Track;
  const factory AutomationTargetDto.bus({
    required int busId,
    required MixerChannelTargetDto mixTarget,
  }) = AutomationTargetDto_Bus;
  const factory AutomationTargetDto.master(MixerChannelTargetDto field0) =
      AutomationTargetDto_Master;
  const factory AutomationTargetDto.tempoBpm() = AutomationTargetDto_TempoBpm;
}

@freezed
sealed class EffectAutomationTargetDto with _$EffectAutomationTargetDto {
  const EffectAutomationTargetDto._();

  const factory EffectAutomationTargetDto.mix() = EffectAutomationTargetDto_Mix;
  const factory EffectAutomationTargetDto.pluginParam({required int paramId}) =
      EffectAutomationTargetDto_PluginParam;
}

@freezed
sealed class MixerChannelTargetDto with _$MixerChannelTargetDto {
  const MixerChannelTargetDto._();

  const factory MixerChannelTargetDto.volume() = MixerChannelTargetDto_Volume;
  const factory MixerChannelTargetDto.pan() = MixerChannelTargetDto_Pan;
  const factory MixerChannelTargetDto.plugin({
    required int effectId,
    required EffectAutomationTargetDto target,
  }) = MixerChannelTargetDto_Plugin;
}
