// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'plugin.dart';
import 'project.dart';
part 'automation.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Fetch the list of (modulation_id, automation_id, automation_lane) where
/// the target is the given track id
Future<List<(int, int, AutomationLaneDto)>> getAutomationLanesForTrack({
  required DawContext ctx,
  required int trackId,
}) => RustLib.instance.api.crateApiAutomationGetAutomationLanesForTrack(
  ctx: ctx,
  trackId: trackId,
);

/// Fetch the list of (modulation_id, automation_id, automation_lane) where
/// the target is the given bus id
Future<List<(int, int, AutomationLaneDto)>> getAutomationLanesForBus({
  required DawContext ctx,
  required int busId,
}) => RustLib.instance.api.crateApiAutomationGetAutomationLanesForBus(
  ctx: ctx,
  busId: busId,
);

Future<(AutomationLaneDto, ModulationLinkDto)> addAutomationLane({
  required DawContext ctx,
  required AutomationTargetDto target,
  required String label,
  required double min,
  required double max,
  required double defaultValue,
}) => RustLib.instance.api.crateApiAutomationAddAutomationLane(
  ctx: ctx,
  target: target,
  label: label,
  min: min,
  max: max,
  defaultValue: defaultValue,
);

/// Fetch all automation lanes across all targets
Future<Map<int, AutomationLaneDto>> getAutomationsLanesAll({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiAutomationGetAutomationsLanesAll(ctx: ctx);

/// Fetch a single automation lane
Future<AutomationLaneDto?> getAutomationLane({
  required DawContext ctx,
  required int laneId,
}) => RustLib.instance.api.crateApiAutomationGetAutomationLane(
  ctx: ctx,
  laneId: laneId,
);

Future<AutomationLaneDto> addAutomationLaneForTrack({
  required DawContext ctx,
  required int trackId,
  required AutomationTargetDto target,
  required String label,
  required double min,
  required double max,
  required double defaultValue,
}) => RustLib.instance.api.crateApiAutomationAddAutomationLaneForTrack(
  ctx: ctx,
  trackId: trackId,
  target: target,
  label: label,
  min: min,
  max: max,
  defaultValue: defaultValue,
);

Future<AutomationLaneDto> addAutomationLaneForBus({
  required DawContext ctx,
  required int busId,
  required AutomationTargetDto target,
  required String label,
  required double min,
  required double max,
  required double defaultValue,
}) => RustLib.instance.api.crateApiAutomationAddAutomationLaneForBus(
  ctx: ctx,
  busId: busId,
  target: target,
  label: label,
  min: min,
  max: max,
  defaultValue: defaultValue,
);

Future<AutomationLaneDto> addNewAutomationPoint({
  required DawContext ctx,
  required int automationId,
  required int timeTicks,
  required double value,
}) => RustLib.instance.api.crateApiAutomationAddNewAutomationPoint(
  ctx: ctx,
  automationId: automationId,
  timeTicks: timeTicks,
  value: value,
);

Future<AutomationLaneDto> removeAutomationPoint({
  required DawContext ctx,
  required int automationId,
  required int id,
}) => RustLib.instance.api.crateApiAutomationRemoveAutomationPoint(
  ctx: ctx,
  automationId: automationId,
  id: id,
);

Future<int> updateAutomationPoint({
  required DawContext ctx,
  required int automationId,
  required int id,
  required int timeTicks,
  required double value,
  required double tension,
}) => RustLib.instance.api.crateApiAutomationUpdateAutomationPoint(
  ctx: ctx,
  automationId: automationId,
  id: id,
  timeTicks: timeTicks,
  value: value,
  tension: tension,
);

/// Get all modulations in the project
Future<Map<int, ModulationLinkDto>> getAllLinkedModulationParams({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiAutomationGetAllLinkedModulationParams(
  ctx: ctx,
);

/// Add generic modulation source
Future<int> addModulationSource({
  required DawContext ctx,
  required ModulationSourceDto source,
}) => RustLib.instance.api.crateApiAutomationAddModulationSource(
  ctx: ctx,
  source: source,
);

/// Remove the modulation source. This function also cascade delete all link
/// with this source
Future<void> removeModulationSource({
  required DawContext ctx,
  required int modId,
}) => RustLib.instance.api.crateApiAutomationRemoveModulationSource(
  ctx: ctx,
  modId: modId,
);

/// Remove modulation link based on queried modulation link id
Future<void> removeModulationLink({
  required DawContext ctx,
  required int modLinkId,
}) => RustLib.instance.api.crateApiAutomationRemoveModulationLink(
  ctx: ctx,
  modLinkId: modLinkId,
);

/// Link the target param to a modulation source
Future<int> linkThisParamToController({
  required DawContext ctx,
  required int sourceId,
  required AutomationTargetDto target,
  required double depth,
  required double baseValue,
}) => RustLib.instance.api.crateApiAutomationLinkThisParamToController(
  ctx: ctx,
  sourceId: sourceId,
  target: target,
  depth: depth,
  baseValue: baseValue,
);

Future<ModulationLinkDto?> getModulationLinkById({
  required DawContext ctx,
  required int linkId,
}) => RustLib.instance.api.crateApiAutomationGetModulationLinkById(
  ctx: ctx,
  linkId: linkId,
);

Future<Map<int, ModulationSourceDto>> getAllModulationSources({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiAutomationGetAllModulationSources(ctx: ctx);

Future<ModulationSourceDto?> getModulationSource({
  required DawContext ctx,
  required int id,
}) => RustLib.instance.api.crateApiAutomationGetModulationSource(
  ctx: ctx,
  id: id,
);

enum AutomationCurveTypeDto { linear, exponential, step }

@freezed
sealed class AutomationLaneDto with _$AutomationLaneDto {
  const factory AutomationLaneDto({
    required int id,
    required String label,
    required List<AutomationPointDto> points,
    required bool enabled,
    required double min,
    required double max,
    required double defaultValue,
  }) = _AutomationLaneDto;
}

@freezed
sealed class AutomationPointDto with _$AutomationPointDto {
  const factory AutomationPointDto({
    required int id,
    required int timeTicks,
    required double value,
    required AutomationCurveTypeDto curveType,
    required double tension,
  }) = _AutomationPointDto;
}

@freezed
sealed class AutomationTargetDto with _$AutomationTargetDto {
  const AutomationTargetDto._();

  const factory AutomationTargetDto.generator({
    required int generatorId,
    required int paramId,
  }) = AutomationTargetDto_Generator;
  const factory AutomationTargetDto.track({
    required int trackId,
    required TrackAutomationTargetDto trackTarget,
  }) = AutomationTargetDto_Track;
  const factory AutomationTargetDto.bus({
    required int busId,
    required MixerChannelParamTargetDto mixTarget,
  }) = AutomationTargetDto_Bus;
  const factory AutomationTargetDto.master(MixerChannelParamTargetDto field0) =
      AutomationTargetDto_Master;
  const factory AutomationTargetDto.tempoBpm() = AutomationTargetDto_TempoBpm;
}

@freezed
sealed class EffectAutomationTargetDto with _$EffectAutomationTargetDto {
  const EffectAutomationTargetDto._();

  const factory EffectAutomationTargetDto.mix() = EffectAutomationTargetDto_Mix;
  const factory EffectAutomationTargetDto.pluginParam({required int paramId}) =
      EffectAutomationTargetDto_PluginParam;
}

@freezed
sealed class MixerChannelParamTargetDto with _$MixerChannelParamTargetDto {
  const MixerChannelParamTargetDto._();

  const factory MixerChannelParamTargetDto.volume() =
      MixerChannelParamTargetDto_Volume;
  const factory MixerChannelParamTargetDto.pan() =
      MixerChannelParamTargetDto_Pan;
  const factory MixerChannelParamTargetDto.plugin({
    required int effectId,
    required EffectAutomationTargetDto target,
  }) = MixerChannelParamTargetDto_Plugin;
}

@freezed
sealed class ModulationLinkDto with _$ModulationLinkDto {
  const factory ModulationLinkDto({
    required int id,
    required int sourceId,
    required AutomationTargetDto target,
    required double depth,
    required double baseValue,
    required int orderIdx,
  }) = _ModulationLinkDto;
}

@freezed
sealed class ModulationSourceDto with _$ModulationSourceDto {
  const ModulationSourceDto._();

  const factory ModulationSourceDto.peakController({
    required UiPluginTarget source,
  }) = ModulationSourceDto_PeakController;
  const factory ModulationSourceDto.automation({required int laneId}) =
      ModulationSourceDto_Automation;
  const factory ModulationSourceDto.lfo({required double rateHz}) =
      ModulationSourceDto_Lfo;
}

@freezed
sealed class TrackAutomationTargetDto with _$TrackAutomationTargetDto {
  const TrackAutomationTargetDto._();

  const factory TrackAutomationTargetDto.mixerChannel(
    MixerChannelParamTargetDto field0,
  ) = TrackAutomationTargetDto_MixerChannel;
}
