// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'plugin.dart';
import 'project.dart';
part 'automation.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `narrow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`

/// Fetch the list of (modulation_id, automation_id, automation_lane) where
/// the target is the given track id
Future<List<(int, int, AutomationLaneDto)>> getAutomationLanesForTrack({
  required DawContext ctx,
  required int trackId,
}) => RustLib.instance.api.crateApiAutomationGetAutomationLanesForTrack(
  ctx: ctx,
  trackId: trackId,
);

/// Fetch the list of (modulation_id, automation_id, automation_lane) where
/// the target is the given bus id
Future<List<(int, int, AutomationLaneDto)>> getAutomationLanesForBus({
  required DawContext ctx,
  required int busId,
}) => RustLib.instance.api.crateApiAutomationGetAutomationLanesForBus(
  ctx: ctx,
  busId: busId,
);

/// Creates an automation lane for `target`.
///
/// `initial_value` is the parameter's current value in its own unit; the parameter normalizes
/// it. `None` starts the lane on the value stored in the project.
Future<(AutomationLaneDto, ModulationLinkDto)> addAutomationLane({
  required DawContext ctx,
  required AutomationTargetDto target,
  required String label,
  double? initialValue,
}) => RustLib.instance.api.crateApiAutomationAddAutomationLane(
  ctx: ctx,
  target: target,
  label: label,
  initialValue: initialValue,
);

/// Fetch all automation lanes across all targets
Future<Map<int, AutomationLaneDto>> getAutomationsLanesAll({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiAutomationGetAutomationsLanesAll(ctx: ctx);

/// Fetch a single automation lane
Future<AutomationLaneDto?> getAutomationLane({
  required DawContext ctx,
  required int laneId,
}) => RustLib.instance.api.crateApiAutomationGetAutomationLane(
  ctx: ctx,
  laneId: laneId,
);

Future<AutomationLaneDto> addAutomationLaneForTrack({
  required DawContext ctx,
  required int trackId,
  required AutomationTargetDto target,
  required String label,
  double? initialValue,
}) => RustLib.instance.api.crateApiAutomationAddAutomationLaneForTrack(
  ctx: ctx,
  trackId: trackId,
  target: target,
  label: label,
  initialValue: initialValue,
);

Future<AutomationLaneDto> addAutomationLaneForBus({
  required DawContext ctx,
  required int busId,
  required AutomationTargetDto target,
  required String label,
  double? initialValue,
}) => RustLib.instance.api.crateApiAutomationAddAutomationLaneForBus(
  ctx: ctx,
  busId: busId,
  target: target,
  label: label,
  initialValue: initialValue,
);

/// ## Overview
///
/// Remove automation lane for target. also cascade remove all modulations linked to it
///
/// ## Returns
///
/// * Tuple of (removed_automation_id, removed_modulation_source_ids, removed_modulation_link_ids)
Future<(int, List<int>, List<int>)> removeAutomationLaneFor({
  required DawContext ctx,
  required AutomationTargetDto target,
}) => RustLib.instance.api.crateApiAutomationRemoveAutomationLaneFor(
  ctx: ctx,
  target: target,
);

/// Sets whether a lane controls its target while preserving its data and link.
Future<AutomationLaneDto> setAutomationLaneEnabled({
  required DawContext ctx,
  required int automationId,
  required bool enabled,
}) => RustLib.instance.api.crateApiAutomationSetAutomationLaneEnabled(
  ctx: ctx,
  automationId: automationId,
  enabled: enabled,
);

Future<AutomationLaneDto> addNewAutomationPoint({
  required DawContext ctx,
  required int automationId,
  required int timeTicks,
  required double value,
}) => RustLib.instance.api.crateApiAutomationAddNewAutomationPoint(
  ctx: ctx,
  automationId: automationId,
  timeTicks: timeTicks,
  value: value,
);

Future<AutomationLaneDto> removeAutomationPoint({
  required DawContext ctx,
  required int automationId,
  required int id,
}) => RustLib.instance.api.crateApiAutomationRemoveAutomationPoint(
  ctx: ctx,
  automationId: automationId,
  id: id,
);

/// Changes the supplied fields of one automation point and returns the updated lane.
Future<AutomationLaneDto> updateAutomationPoint({
  required DawContext ctx,
  required int automationId,
  required int id,
  int? timeTicks,
  double? value,
  double? tension,
  AutomationCurveTypeDto? curveType,
  BezierHandlesDto? handles,
}) => RustLib.instance.api.crateApiAutomationUpdateAutomationPoint(
  ctx: ctx,
  automationId: automationId,
  id: id,
  timeTicks: timeTicks,
  value: value,
  tension: tension,
  curveType: curveType,
  handles: handles,
);

/// Copies the curve of a lane between two ticks. Returned points have times relative to the
/// range start; a point is added on each edge the range cuts through a segment.
Future<List<AutomationPointDto>> copyAutomationRange({
  required DawContext ctx,
  required int automationId,
  required int startTick,
  required int endTick,
}) => RustLib.instance.api.crateApiAutomationCopyAutomationRange(
  ctx: ctx,
  automationId: automationId,
  startTick: startTick,
  endTick: endTick,
);

/// Removes every point of a lane between two ticks as one undo step.
Future<AutomationLaneDto> deleteAutomationRange({
  required DawContext ctx,
  required int automationId,
  required int startTick,
  required int endTick,
}) => RustLib.instance.api.crateApiAutomationDeleteAutomationRange(
  ctx: ctx,
  automationId: automationId,
  startTick: startTick,
  endTick: endTick,
);

/// Pastes a copied curve at `at_tick` as one undo step, replacing the points under it.
///
/// `length_ticks` is the length of the copied range; `target_length` stretches the curve to
/// another length.
Future<AutomationLaneDto> pasteAutomationPoints({
  required DawContext ctx,
  required int automationId,
  required int atTick,
  required List<AutomationPointDto> points,
  required int lengthTicks,
  int? targetLength,
}) => RustLib.instance.api.crateApiAutomationPasteAutomationPoints(
  ctx: ctx,
  automationId: automationId,
  atTick: atTick,
  points: points,
  lengthTicks: lengthTicks,
  targetLength: targetLength,
);

/// Formats a lane's normalized value in the unit of the parameter it automates.
String automationValueText({
  required DawContext ctx,
  required int automationId,
  required double normalized,
}) => RustLib.instance.api.crateApiAutomationAutomationValueText(
  ctx: ctx,
  automationId: automationId,
  normalized: normalized,
);

/// Parses text typed in the unit of a lane's parameter into a normalized lane value.
double parseAutomationValue({
  required DawContext ctx,
  required int automationId,
  required String text,
}) => RustLib.instance.api.crateApiAutomationParseAutomationValue(
  ctx: ctx,
  automationId: automationId,
  text: text,
);

/// Samples a lane's curve at `sample_count` evenly spaced ticks from `start_tick` to `end_tick`
/// inclusive. `points` must be in lane order. Returns no samples for a lane without points.
Float32List sampleAutomationCurve({
  required List<AutomationPointDto> points,
  required double startTick,
  required double endTick,
  required int sampleCount,
}) => RustLib.instance.api.crateApiAutomationSampleAutomationCurve(
  points: points,
  startTick: startTick,
  endTick: endTick,
  sampleCount: sampleCount,
);

/// Value at the time midpoint of every segment of a lane, one entry per pair of consecutive
/// points. Editors place each segment's tension handle on it.
Float32List automationSegmentMidpoints({
  required List<AutomationPointDto> points,
}) => RustLib.instance.api.crateApiAutomationAutomationSegmentMidpoints(
  points: points,
);

/// Describes which segment controls a curve type responds to.
AutomationCurveTraitsDto automationCurveTraits({
  required AutomationCurveTypeDto curveType,
}) => RustLib.instance.api.crateApiAutomationAutomationCurveTraits(
  curveType: curveType,
);

/// Step or cycle count that `tension` selects for count-driven curve types.
int automationTensionCount({required double tension}) => RustLib.instance.api
    .crateApiAutomationAutomationTensionCount(tension: tension);

/// Get all modulations in the project
Future<Map<int, ModulationLinkDto>> getAllLinkedModulationParams({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiAutomationGetAllLinkedModulationParams(
  ctx: ctx,
);

/// Add generic modulation source
Future<int> addModulationSource({
  required DawContext ctx,
  required ModulationSourceDto source,
}) => RustLib.instance.api.crateApiAutomationAddModulationSource(
  ctx: ctx,
  source: source,
);

/// Remove the modulation source. This function also cascade delete all link
/// with this source
Future<void> removeModulationSource({
  required DawContext ctx,
  required int modId,
}) => RustLib.instance.api.crateApiAutomationRemoveModulationSource(
  ctx: ctx,
  modId: modId,
);

/// Remove modulation link based on queried modulation link id
Future<void> removeModulationLink({
  required DawContext ctx,
  required int modLinkId,
}) => RustLib.instance.api.crateApiAutomationRemoveModulationLink(
  ctx: ctx,
  modLinkId: modLinkId,
);

/// Link the target param to a modulation source
Future<int> linkThisParamToController({
  required DawContext ctx,
  required int sourceId,
  required AutomationTargetDto target,
  required double depth,
  required double baseValue,
}) => RustLib.instance.api.crateApiAutomationLinkThisParamToController(
  ctx: ctx,
  sourceId: sourceId,
  target: target,
  depth: depth,
  baseValue: baseValue,
);

Future<ModulationLinkDto?> getModulationLinkById({
  required DawContext ctx,
  required int linkId,
}) => RustLib.instance.api.crateApiAutomationGetModulationLinkById(
  ctx: ctx,
  linkId: linkId,
);

Future<Map<int, ModulationSourceDto>> getAllModulationSources({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiAutomationGetAllModulationSources(ctx: ctx);

Future<ModulationSourceDto?> getModulationSource({
  required DawContext ctx,
  required int id,
}) => RustLib.instance.api.crateApiAutomationGetModulationSource(
  ctx: ctx,
  id: id,
);

/// Which segment controls a curve type responds to, so editors stay generic over curve types.
@freezed
sealed class AutomationCurveTraitsDto with _$AutomationCurveTraitsDto {
  const factory AutomationCurveTraitsDto({
    required bool supportsTension,
    required bool tensionInverted,
    required bool tensionIsCount,
    required bool usesHandles,
  }) = _AutomationCurveTraitsDto;
}

enum AutomationCurveTypeDto {
  linear,
  exponential,
  step,
  logarithmic,
  sCurve,
  bezier,
  stairs,
  smoothStairs,
  pulse,
  wave,
  triangle,
  halfSine,
}

@freezed
sealed class AutomationLaneDto with _$AutomationLaneDto {
  const factory AutomationLaneDto({
    required int id,
    required String label,
    required List<AutomationPointDto> points,
    required bool enabled,
    required double defaultValue,
  }) = _AutomationLaneDto;
}

@freezed
sealed class AutomationPointDto with _$AutomationPointDto {
  const factory AutomationPointDto({
    required int id,
    required int timeTicks,
    required double value,
    required AutomationCurveTypeDto curveType,
    required double tension,
    BezierHandlesDto? handles,
  }) = _AutomationPointDto;
}

@freezed
sealed class AutomationTargetDto with _$AutomationTargetDto {
  const AutomationTargetDto._();

  const factory AutomationTargetDto.generator({
    required int generatorId,
    required int paramId,
  }) = AutomationTargetDto_Generator;
  const factory AutomationTargetDto.track({
    required int trackId,
    required TrackAutomationTargetDto trackTarget,
  }) = AutomationTargetDto_Track;
  const factory AutomationTargetDto.bus({
    required int busId,
    required MixerChannelParamTargetDto mixTarget,
  }) = AutomationTargetDto_Bus;
  const factory AutomationTargetDto.master(MasterAutomationTargetDto field0) =
      AutomationTargetDto_Master;
}

/// Control handles of a Bezier segment. `x` is a fraction of the segment's duration and `y` a
/// normalized lane value, both 0.0 to 1.0.
@freezed
sealed class BezierHandlesDto with _$BezierHandlesDto {
  const factory BezierHandlesDto({
    required double x1,
    required double y1,
    required double x2,
    required double y2,
  }) = _BezierHandlesDto;
}

@freezed
sealed class EffectAutomationTargetDto with _$EffectAutomationTargetDto {
  const EffectAutomationTargetDto._();

  const factory EffectAutomationTargetDto.mix() = EffectAutomationTargetDto_Mix;
  const factory EffectAutomationTargetDto.pluginParam({required int paramId}) =
      EffectAutomationTargetDto_PluginParam;
}

@freezed
sealed class MasterAutomationTargetDto with _$MasterAutomationTargetDto {
  const MasterAutomationTargetDto._();

  const factory MasterAutomationTargetDto.mixerChannel(
    MixerChannelParamTargetDto field0,
  ) = MasterAutomationTargetDto_MixerChannel;
  const factory MasterAutomationTargetDto.tempoBpm() =
      MasterAutomationTargetDto_TempoBpm;
}

@freezed
sealed class MixerChannelParamTargetDto with _$MixerChannelParamTargetDto {
  const MixerChannelParamTargetDto._();

  const factory MixerChannelParamTargetDto.volume() =
      MixerChannelParamTargetDto_Volume;
  const factory MixerChannelParamTargetDto.pan() =
      MixerChannelParamTargetDto_Pan;
  const factory MixerChannelParamTargetDto.plugin({
    required int effectId,
    required EffectAutomationTargetDto target,
  }) = MixerChannelParamTargetDto_Plugin;
}

@freezed
sealed class ModulationLinkDto with _$ModulationLinkDto {
  const factory ModulationLinkDto({
    required int id,
    required int sourceId,
    required AutomationTargetDto target,
    required double depth,
    required double baseValue,
    required int orderIdx,
  }) = _ModulationLinkDto;
}

@freezed
sealed class ModulationSourceDto with _$ModulationSourceDto {
  const ModulationSourceDto._();

  const factory ModulationSourceDto.peakController({
    required UiPluginTarget source,
  }) = ModulationSourceDto_PeakController;
  const factory ModulationSourceDto.automation({required int laneId}) =
      ModulationSourceDto_Automation;
  const factory ModulationSourceDto.lfo({required double rateHz}) =
      ModulationSourceDto_Lfo;
}

/// Automation removed as part of another project operation, such as deleting an effect.
@freezed
sealed class RemovedAutomationDto with _$RemovedAutomationDto {
  const factory RemovedAutomationDto({
    required List<int> automationLaneIds,
    required List<int> modulationSourceIds,
    required List<int> modulationLinkIds,
  }) = _RemovedAutomationDto;
}

@freezed
sealed class TrackAutomationTargetDto with _$TrackAutomationTargetDto {
  const TrackAutomationTargetDto._();

  const factory TrackAutomationTargetDto.mixerChannel(
    MixerChannelParamTargetDto field0,
  ) = TrackAutomationTargetDto_MixerChannel;
}
