// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'plugin.dart';
import 'project.dart';
part 'external_plugins.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

Future<List<String>> defaultPluginScanPaths() =>
    RustLib.instance.api.crateApiExternalPluginsDefaultPluginScanPaths();

Future<UiPluginScanSettings> pluginScanSettings() =>
    RustLib.instance.api.crateApiExternalPluginsPluginScanSettings();

Future<UiPluginScanSettings> savePluginScanSettings({
  required List<String> directories,
  required int timeoutSeconds,
}) => RustLib.instance.api.crateApiExternalPluginsSavePluginScanSettings(
  directories: directories,
  timeoutSeconds: timeoutSeconds,
);

/// Starts a worker and publishes progress events; never retains the project context.
Stream<UiPluginScanEvent> scanExternalPlugins({
  required List<String> directories,
  required int timeoutSeconds,
  required bool retryQuarantined,
}) => RustLib.instance.api.crateApiExternalPluginsScanExternalPlugins(
  directories: directories,
  timeoutSeconds: timeoutSeconds,
  retryQuarantined: retryQuarantined,
);

Future<bool> cancelExternalPluginScan({required int id}) => RustLib.instance.api
    .crateApiExternalPluginsCancelExternalPluginScan(id: id);

Future<UiExternalPluginDescriptor?> externalPluginDescriptor({
  required DawContext ctx,
  required UiPluginTarget target,
}) => RustLib.instance.api.crateApiExternalPluginsExternalPluginDescriptor(
  ctx: ctx,
  target: target,
);

Future<List<UiExternalPluginEntry>> refreshExternalPluginCatalog({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiExternalPluginsRefreshExternalPluginCatalog(
  ctx: ctx,
);

Future<UiExternalPluginCapabilities> externalPluginCapabilities({
  required DawContext ctx,
  required UiPluginTarget target,
}) => RustLib.instance.api.crateApiExternalPluginsExternalPluginCapabilities(
  ctx: ctx,
  target: target,
);

/// Reopening an existing editor brings its native window to the foreground.
Future<void> openExternalPluginEditor({
  required DawContext ctx,
  required UiPluginTarget target,
}) => RustLib.instance.api.crateApiExternalPluginsOpenExternalPluginEditor(
  ctx: ctx,
  target: target,
);

Future<void> closeExternalPluginEditor({
  required DawContext ctx,
  required UiPluginTarget target,
}) => RustLib.instance.api.crateApiExternalPluginsCloseExternalPluginEditor(
  ctx: ctx,
  target: target,
);

Future<void> setExternalPluginParameter({
  required DawContext ctx,
  required UiPluginTarget target,
  required int parameter,
  required double value,
}) => RustLib.instance.api.crateApiExternalPluginsSetExternalPluginParameter(
  ctx: ctx,
  target: target,
  parameter: parameter,
  value: value,
);

Future<String> externalPluginParameterText({
  required DawContext ctx,
  required UiPluginTarget target,
  required int parameter,
  required double value,
}) => RustLib.instance.api.crateApiExternalPluginsExternalPluginParameterText(
  ctx: ctx,
  target: target,
  parameter: parameter,
  value: value,
);

Future<double> parseExternalPluginParameter({
  required DawContext ctx,
  required UiPluginTarget target,
  required int parameter,
  required String text,
}) => RustLib.instance.api.crateApiExternalPluginsParseExternalPluginParameter(
  ctx: ctx,
  target: target,
  parameter: parameter,
  text: text,
);

Future<double> convertExternalPluginParameter({
  required DawContext ctx,
  required UiPluginTarget target,
  required int parameter,
  required double value,
  required bool toNormalized,
}) =>
    RustLib.instance.api.crateApiExternalPluginsConvertExternalPluginParameter(
      ctx: ctx,
      target: target,
      parameter: parameter,
      value: value,
      toNormalized: toNormalized,
    );

Future<String?> externalPluginFailure({
  required DawContext ctx,
  required UiPluginTarget target,
}) => RustLib.instance.api.crateApiExternalPluginsExternalPluginFailure(
  ctx: ctx,
  target: target,
);

Future<void> retryExternalPlugin({
  required DawContext ctx,
  required UiPluginTarget target,
}) => RustLib.instance.api.crateApiExternalPluginsRetryExternalPlugin(
  ctx: ctx,
  target: target,
);

@freezed
sealed class UiExternalPluginCapabilities with _$UiExternalPluginCapabilities {
  const factory UiExternalPluginCapabilities({
    required bool controller,
    required bool editor,
    required bool sidechain,
  }) = _UiExternalPluginCapabilities;
}

@freezed
sealed class UiExternalPluginDescriptor with _$UiExternalPluginDescriptor {
  const factory UiExternalPluginDescriptor({
    required UiExternalPluginFormat format,
    required String nativeId,
    required String path,
    required String name,
    required String vendor,
    required String version,
    required bool instrument,
  }) = _UiExternalPluginDescriptor;
}

@freezed
sealed class UiExternalPluginEntry with _$UiExternalPluginEntry {
  const factory UiExternalPluginEntry({
    required int id,
    required bool available,
    required UiExternalPluginDescriptor descriptor,
  }) = _UiExternalPluginEntry;
}

enum UiExternalPluginFormat { vst3, lv2, clap, au }

@freezed
sealed class UiPluginScanEvent with _$UiPluginScanEvent {
  const UiPluginScanEvent._();

  const factory UiPluginScanEvent.started({required int id}) =
      UiPluginScanEvent_Started;
  const factory UiPluginScanEvent.progress({
    required int completed,
    required int total,
    required int discovered,
    required String path,
    String? error,
  }) = UiPluginScanEvent_Progress;
  const factory UiPluginScanEvent.finished({
    required List<UiExternalPluginDescriptor> plugins,
    required List<UiPluginScanFailure> failures,
    required bool cancelled,
  }) = UiPluginScanEvent_Finished;
  const factory UiPluginScanEvent.failed({required String message}) =
      UiPluginScanEvent_Failed;
}

@freezed
sealed class UiPluginScanFailure with _$UiPluginScanFailure {
  const factory UiPluginScanFailure({
    required String path,
    required String reason,
  }) = _UiPluginScanFailure;
}

@freezed
sealed class UiPluginScanSettings with _$UiPluginScanSettings {
  const factory UiPluginScanSettings({
    required List<String> directories,
    required int timeoutSeconds,
  }) = _UiPluginScanSettings;
}
