// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'jobs.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `frb_runtime_handle`, `run_job`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StreamJobSink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `send`

/// Streams lifecycle events of every background job. A new subscription replaces the old one.
Stream<UiJobEvent> subscribeJobEvents() =>
    RustLib.instance.api.crateApiJobsSubscribeJobEvents();

/// Asks a background job to stop. Returns `false` when no unfinished job has that id.
Future<bool> cancelJob({required int id}) =>
    RustLib.instance.api.crateApiJobsCancelJob(id: id);

@freezed
sealed class UiJobEvent with _$UiJobEvent {
  const factory UiJobEvent({
    required int id,
    required UiJobKind kind,
    required UiJobTarget target,
    required UiJobState state,
  }) = _UiJobEvent;
}

enum UiJobKind {
  projectExport,
  bounce,
  projectLoad,
  projectSave,
  projectRestore,
  audioImport,
  waveformRender,
  tempoDetection,
  pluginInstall,
  pluginRemoval,
  pluginRetry,
  pluginReconfigure,
  pluginScan,
}

@freezed
sealed class UiJobState with _$UiJobState {
  const UiJobState._();

  const factory UiJobState.queued() = UiJobState_Queued;
  const factory UiJobState.running() = UiJobState_Running;
  const factory UiJobState.progress({
    required String stage,
    required double fraction,
  }) = UiJobState_Progress;
  const factory UiJobState.completed() = UiJobState_Completed;
  const factory UiJobState.failed({required String message}) =
      UiJobState_Failed;
  const factory UiJobState.cancelled() = UiJobState_Cancelled;
}

@freezed
sealed class UiJobTarget with _$UiJobTarget {
  const UiJobTarget._();

  const factory UiJobTarget.none() = UiJobTarget_None;
  const factory UiJobTarget.project() = UiJobTarget_Project;
  const factory UiJobTarget.source({required int sourceId}) =
      UiJobTarget_Source;
}
