// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'logging.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `send_batch`

/// Streams batches of Rust log records to Flutter.
///
/// Records logged before the first subscription (or while no Dart listener is
/// attached, e.g. across a hot restart) are retained in a bounded backlog and
/// delivered first. Subscribing again replaces the previous stream.
Stream<List<RustLogEntryDto>> subscribeRustLogs() =>
    RustLib.instance.api.crateApiLoggingSubscribeRustLogs();

/// One Rust `log` record forwarded to the Flutter log viewer.
@freezed
sealed class RustLogEntryDto with _$RustLogEntryDto {
  const factory RustLogEntryDto({
    required int timestampMillis,
    required RustLogLevel level,
    required String target,
    required String message,
  }) = _RustLogEntryDto;
}

enum RustLogLevel { trace, debug, info, warn, error }
