// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'automation.dart';
import 'mixer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'pattern.dart';
import 'plugin.dart';
import 'project.dart';
import 'timeline.dart';
part 'mitigation.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `auto_save_once`, `inner_context`, `load_recovered_project_blocking`, `run_auto_save_worker`, `start_auto_save_worker`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AutoSaveOutcome`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// Configures crash reporting and auto save recovery under `support_dir`, records Ctrl+C as a
/// forced shutdown, then starts the auto save worker. Call once after the project is initialized;
/// later calls return the current state.
Future<UiStartupRecovery> configureMitigation({
  required DawContext ctx,
  required String supportDir,
  required String appVersion,
}) => RustLib.instance.api.crateApiMitigationConfigureMitigation(
  ctx: ctx,
  supportDir: supportDir,
  appVersion: appVersion,
);

/// Validates and applies auto save settings, and wakes the worker to use the new interval.
Future<UiAutoSaveSettings> setAutoSaveSettings({
  required DawContext ctx,
  required UiAutoSaveSettings settings,
}) => RustLib.instance.api.crateApiMitigationSetAutoSaveSettings(
  ctx: ctx,
  settings: settings,
);

/// Writes a crash report for an error caught by a Flutter error handler.
void recordFlutterCrash({
  required UiFlutterCrashKind kind,
  String? sourceLibrary,
  required String message,
  String? stack,
}) => RustLib.instance.api.crateApiMitigationRecordFlutterCrash(
  kind: kind,
  sourceLibrary: sourceLibrary,
  message: message,
  stack: stack,
);

/// Lists stored crash reports, newest first.
Future<List<UiCrashReportSummary>> listCrashReports() =>
    RustLib.instance.api.crateApiMitigationListCrashReports();

/// Deletes one stored crash report.
Future<void> removeCrashReport({required String id}) =>
    RustLib.instance.api.crateApiMitigationRemoveCrashReport(id: id);

/// Copies one crash report's JSON to `destination`.
Future<void> exportCrashReport({
  required String id,
  required String destination,
}) => RustLib.instance.api.crateApiMitigationExportCrashReport(
  id: id,
  destination: destination,
);

/// Replaces the live project with the auto saved copy. The recovered project is marked unsaved
/// and keeps the file path of the project it was auto saved from.
Future<UiApplicationState> loadRecoveredProject({required DawContext ctx}) =>
    RustLib.instance.api.crateApiMitigationLoadRecoveredProject(ctx: ctx);

/// Deletes the auto saved copy.
Future<void> discardRecoveredProject({required DawContext ctx}) =>
    RustLib.instance.api.crateApiMitigationDiscardRecoveredProject(ctx: ctx);

/// Suspends the session while a mobile app is backgrounded, and resumes it on return, so an OS
/// kill in the background is not reported as a crash. The recovery copy is kept.
Future<void> setSessionSuspended({
  required DawContext ctx,
  required bool suspended,
}) => RustLib.instance.api.crateApiMitigationSetSessionSuspended(
  ctx: ctx,
  suspended: suspended,
);

/// Ends the session cleanly so the next launch does not report a crash or offer recovery.
///
/// Stops background jobs first so none of them touches the project after this point.
Future<void> markCleanShutdown({required DawContext ctx}) =>
    RustLib.instance.api.crateApiMitigationMarkCleanShutdown(ctx: ctx);

/// Auto save settings as edited in General Settings.
@freezed
sealed class UiAutoSaveSettings with _$UiAutoSaveSettings {
  const factory UiAutoSaveSettings({
    required bool isEnabled,
    required int intervalSeconds,
  }) = _UiAutoSaveSettings;
}

/// One stored crash report, summarized for the recovery dialog.
@freezed
sealed class UiCrashReportSummary with _$UiCrashReportSummary {
  const factory UiCrashReportSummary({
    required String id,
    required int code,
    required String summary,
    required int occurredAtMillis,
    required String appVersion,
  }) = _UiCrashReportSummary;
}

/// Which Flutter error handler caught the crash.
enum UiFlutterCrashKind {
  /// `FlutterError.onError`.
  frameworkError,

  /// `PlatformDispatcher.onError`.
  uncaughtAsync,
}

/// Auto saved project that can be recovered.
@freezed
sealed class UiRecoveryInfo with _$UiRecoveryInfo {
  const factory UiRecoveryInfo({
    required String projectName,
    String? originalPath,
    required int savedAtMillis,
  }) = _UiRecoveryInfo;
}

/// What the previous run left behind, reported once at startup.
@freezed
sealed class UiStartupRecovery with _$UiStartupRecovery {
  const factory UiStartupRecovery({
    required bool previousSessionUnclean,
    required bool previousSessionForced,
    UiRecoveryInfo? recovery,
    required List<UiCrashReportSummary> crashReports,
  }) = _UiStartupRecovery;
}
