// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mixer.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Opens a stream that continuously polls the audio-thread feedback ring buffer
/// for `MixerChannelSnapshot` events and forwards them to Flutter.
///
/// Call `query_mixer_channel(target)` to request a snapshot; the audio thread
/// will push the response into the feedback ring buffer, and it will arrive
/// here within one polling interval (~16 ms).
///
/// This mirrors the pattern used by `create_plugin_message_stream` for plugin
/// parameters — there is no special direct-callback path; everything goes
/// through the shared `PENDING_FEEDBACK` buffer.
///
/// The polling thread terminates automatically when Flutter closes the stream.
Stream<UiMixerChannelSnapshot> createMixerSnapshotStream() =>
    RustLib.instance.api.crateApiMixerCreateMixerSnapshotStream();

/// Set a single DSP parameter on a mixer channel.
/// Routes through the audio thread ring buffer; AppState is only updated on save.
Future<void> setMixerChannelParam({
  required UiMixerChannelTarget target,
  required UiMixerChannelParams param,
}) => RustLib.instance.api.crateApiMixerSetMixerChannelParam(
  target: target,
  param: param,
);

/// Request a full snapshot of a mixer channel's current DSP state.
/// Results arrive asynchronously via the `create_mixer_snapshot_stream` polling stream.
Future<void> queryMixerChannel({required UiMixerChannelTarget target}) =>
    RustLib.instance.api.crateApiMixerQueryMixerChannel(target: target);

/// **GETTER: Fetch the mixer state**
Future<UiMixerState> getMixerState() =>
    RustLib.instance.api.crateApiMixerGetMixerState();

/// **GETTER: Fetch a specific mixer channel**
Future<UiMixerChannel> getMixerChannel({required int trackId}) =>
    RustLib.instance.api.crateApiMixerGetMixerChannel(trackId: trackId);

Future<(UiMixerChannel, List<UiEffectInstance>)> getMixerChannelPopulated({
  required int trackId,
}) => RustLib.instance.api.crateApiMixerGetMixerChannelPopulated(
  trackId: trackId,
);

/// **GETTER: Fetch the master bus**
Future<UiMixerChannel> getMasterBus() =>
    RustLib.instance.api.crateApiMixerGetMasterBus();

Future<List<UiEffectInstance>> getMasterBusPopulated() =>
    RustLib.instance.api.crateApiMixerGetMasterBusPopulated();

/// **GETTER: Fetch all buses**
Future<Map<int, UiBus>> getBuses() =>
    RustLib.instance.api.crateApiMixerGetBuses();

/// **GETTER: Fetch the routing matrix**
Future<List<UiRoutingConnection>> getRoutingMatrix() =>
    RustLib.instance.api.crateApiMixerGetRoutingMatrix();

/// Get track channel's parameter specs
Future<List<ParameterSpecDTO>?> getTrackMixerChannelSpecs({
  required int trackId,
}) => RustLib.instance.api.crateApiMixerGetTrackMixerChannelSpecs(
  trackId: trackId,
);

/// Get bus channel's parameter specs
Future<List<ParameterSpecDTO>?> getBusMixerChannelSpecs({required int busId}) =>
    RustLib.instance.api.crateApiMixerGetBusMixerChannelSpecs(busId: busId);

/// get master channel's parameter specs
Future<List<ParameterSpecDTO>> getMasterChannelSpecs() =>
    RustLib.instance.api.crateApiMixerGetMasterChannelSpecs();

/// Add an effect to a mixer channel by its registry ID (preferred method).
Future<void> addEffectToMixerChannelById({
  required int trackId,
  required int registryId,
}) => RustLib.instance.api.crateApiMixerAddEffectToMixerChannelById(
  trackId: trackId,
  registryId: registryId,
);

Future<void> removeEffectFromMixerChannel({
  required int trackId,
  required int effectInstanceId,
}) => RustLib.instance.api.crateApiMixerRemoveEffectFromMixerChannel(
  trackId: trackId,
  effectInstanceId: effectInstanceId,
);

Future<void> addEffectToMasterBus({required int registryId}) => RustLib
    .instance
    .api
    .crateApiMixerAddEffectToMasterBus(registryId: registryId);

Future<void> removeEffectFromMasterBus({required int effectInstanceId}) =>
    RustLib.instance.api.crateApiMixerRemoveEffectFromMasterBus(
      effectInstanceId: effectInstanceId,
    );

/// Create a new mixer bus and return its ID.
Future<int> createBus({required String name}) =>
    RustLib.instance.api.crateApiMixerCreateBus(name: name);

/// Delete a mixer bus.
Future<void> deleteBus({required int busId}) =>
    RustLib.instance.api.crateApiMixerDeleteBus(busId: busId);

/// Add an effect to a bus by its registry ID.
Future<void> addEffectToBus({required int busId, required int registryId}) =>
    RustLib.instance.api.crateApiMixerAddEffectToBus(
      busId: busId,
      registryId: registryId,
    );

Future<void> renameBus({required int busId, required String newName}) =>
    RustLib.instance.api.crateApiMixerRenameBus(busId: busId, newName: newName);

Future<List<UiRoutingConnection>> getChannelDestinations({
  required bool isBus,
  required int channelId,
}) => RustLib.instance.api.crateApiMixerGetChannelDestinations(
  isBus: isBus,
  channelId: channelId,
);

/// Set routing: source → destination with send level.
Future<void> setRouting({
  required UiRoutingNode source,
  required UiRoutingNode destination,
  required double sendLevel,
  required bool isSend,
}) => RustLib.instance.api.crateApiMixerSetRouting(
  source: source,
  destination: destination,
  sendLevel: sendLevel,
  isSend: isSend,
);

/// Remove a routing connection.
Future<void> removeRouting({
  required UiRoutingNode source,
  required UiRoutingNode destination,
  required bool isSend,
}) => RustLib.instance.api.crateApiMixerRemoveRouting(
  source: source,
  destination: destination,
  isSend: isSend,
);

Future<void> updateRouting({required UiRoutingConnection conn}) =>
    RustLib.instance.api.crateApiMixerUpdateRouting(conn: conn);

class ParameterSpecDTO {
  final int id;
  final String name;
  final String group;
  final double value;
  final double min;
  final double max;
  final double defaultValue;
  final double step;
  final ParameterValueTypeDTO valueType;
  final List<String> choices;

  const ParameterSpecDTO({
    required this.id,
    required this.name,
    required this.group,
    required this.value,
    required this.min,
    required this.max,
    required this.defaultValue,
    required this.step,
    required this.valueType,
    required this.choices,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      group.hashCode ^
      value.hashCode ^
      min.hashCode ^
      max.hashCode ^
      defaultValue.hashCode ^
      step.hashCode ^
      valueType.hashCode ^
      choices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParameterSpecDTO &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          group == other.group &&
          value == other.value &&
          min == other.min &&
          max == other.max &&
          defaultValue == other.defaultValue &&
          step == other.step &&
          valueType == other.valueType &&
          choices == other.choices;
}

enum ParameterValueTypeDTO { float, int, bool, choice }

/// UI representation of a mixer bus.
class UiBus {
  final int id;
  final String name;
  final UiMixerChannel channel;

  const UiBus({required this.id, required this.name, required this.channel});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ channel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiBus &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          channel == other.channel;
}

class UiEffectInstance {
  final int id;
  final String name;

  const UiEffectInstance({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiEffectInstance &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class UiEffectSummary {
  final int id;
  final int registryId;
  final String name;

  const UiEffectSummary({
    required this.id,
    required this.registryId,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ registryId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiEffectSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          registryId == other.registryId &&
          name == other.name;
}

/// UI representation of a mixer channel.
class UiMixerChannel {
  final double volume;
  final double pan;
  final bool mute;
  final bool solo;
  final bool invertedPhase;

  /// List of effect summaries (ID and name).
  final List<UiEffectSummary> effects;

  const UiMixerChannel({
    required this.volume,
    required this.pan,
    required this.mute,
    required this.solo,
    required this.invertedPhase,
    required this.effects,
  });

  @override
  int get hashCode =>
      volume.hashCode ^
      pan.hashCode ^
      mute.hashCode ^
      solo.hashCode ^
      invertedPhase.hashCode ^
      effects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiMixerChannel &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          pan == other.pan &&
          mute == other.mute &&
          solo == other.solo &&
          invertedPhase == other.invertedPhase &&
          effects == other.effects;
}

@freezed
sealed class UiMixerChannelParams with _$UiMixerChannelParams {
  const UiMixerChannelParams._();

  const factory UiMixerChannelParams.volume(double field0) =
      UiMixerChannelParams_Volume;
  const factory UiMixerChannelParams.pan(double field0) =
      UiMixerChannelParams_Pan;
  const factory UiMixerChannelParams.mute(bool field0) =
      UiMixerChannelParams_Mute;
  const factory UiMixerChannelParams.invertedPhase(bool field0) =
      UiMixerChannelParams_InvertedPhase;
  const factory UiMixerChannelParams.solo(bool field0) =
      UiMixerChannelParams_Solo;
}

/// Full DSP state snapshot of a mixer channel, polled via
/// poll_mixer_channel_feedback() after calling query_mixer_channel().
class UiMixerChannelSnapshot {
  final int trackId;
  final int? busId;
  final bool isMaster;
  final double volume;
  final double pan;
  final bool mute;
  final bool solo;
  final bool invertedPhase;

  const UiMixerChannelSnapshot({
    required this.trackId,
    this.busId,
    required this.isMaster,
    required this.volume,
    required this.pan,
    required this.mute,
    required this.solo,
    required this.invertedPhase,
  });

  @override
  int get hashCode =>
      trackId.hashCode ^
      busId.hashCode ^
      isMaster.hashCode ^
      volume.hashCode ^
      pan.hashCode ^
      mute.hashCode ^
      solo.hashCode ^
      invertedPhase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiMixerChannelSnapshot &&
          runtimeType == other.runtimeType &&
          trackId == other.trackId &&
          busId == other.busId &&
          isMaster == other.isMaster &&
          volume == other.volume &&
          pan == other.pan &&
          mute == other.mute &&
          solo == other.solo &&
          invertedPhase == other.invertedPhase;
}

@freezed
sealed class UiMixerChannelTarget with _$UiMixerChannelTarget {
  const UiMixerChannelTarget._();

  const factory UiMixerChannelTarget.track(int field0) =
      UiMixerChannelTarget_Track;
  const factory UiMixerChannelTarget.bus(int field0) = UiMixerChannelTarget_Bus;
  const factory UiMixerChannelTarget.master() = UiMixerChannelTarget_Master;
}

/// UI representation of the mixer state.
class UiMixerState {
  final Map<int, UiMixerChannel> channels;
  final UiMixerChannel masterBus;
  final Map<int, UiBus> buses;
  final List<UiRoutingConnection> routing;

  const UiMixerState.raw({
    required this.channels,
    required this.masterBus,
    required this.buses,
    required this.routing,
  });

  factory UiMixerState() => RustLib.instance.api.crateApiMixerUiMixerStateNew();

  static UiMixerState newWithParam({
    required Map<int, UiMixerChannel> channels,
    required UiMixerChannel masterBus,
    required Map<int, UiBus> buses,
    required List<UiRoutingConnection> routing,
  }) => RustLib.instance.api.crateApiMixerUiMixerStateNewWithParam(
    channels: channels,
    masterBus: masterBus,
    buses: buses,
    routing: routing,
  );

  @override
  int get hashCode =>
      channels.hashCode ^
      masterBus.hashCode ^
      buses.hashCode ^
      routing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiMixerState &&
          runtimeType == other.runtimeType &&
          channels == other.channels &&
          masterBus == other.masterBus &&
          buses == other.buses &&
          routing == other.routing;
}

/// UI representation of a routing connection.
class UiRoutingConnection {
  final UiRoutingNode source;
  final UiRoutingNode destination;
  final double sendLevel;
  final bool isSend;

  const UiRoutingConnection({
    required this.source,
    required this.destination,
    required this.sendLevel,
    required this.isSend,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      destination.hashCode ^
      sendLevel.hashCode ^
      isSend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiRoutingConnection &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          destination == other.destination &&
          sendLevel == other.sendLevel &&
          isSend == other.isSend;
}

@freezed
sealed class UiRoutingNode with _$UiRoutingNode {
  const UiRoutingNode._();

  const factory UiRoutingNode.track(int field0) = UiRoutingNode_Track;
  const factory UiRoutingNode.bus(int field0) = UiRoutingNode_Bus;
  const factory UiRoutingNode.master() = UiRoutingNode_Master;
  const factory UiRoutingNode.pluginSidechain() = UiRoutingNode_PluginSidechain;
}
