// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'monitor.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

Stream<PerformanceMetricsDTO> startPerformanceMonitor() =>
    RustLib.instance.api.crateApiMonitorStartPerformanceMonitor();

@freezed
sealed class PerformanceMetricsDTO with _$PerformanceMetricsDTO {
  const factory PerformanceMetricsDTO({
    required double osCpuUsage,
    required double ramUsageMb,
    required double totalRamMb,
    required double dspHeadroom,
  }) = _PerformanceMetricsDTO;
}
