// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pattern.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `from`, `from`

Future<UiPattern> getPattern({required int patternId}) =>
    RustLib.instance.api.crateApiPatternGetPattern(patternId: patternId);

Future<Map<int, UiPattern>> getPatterns() =>
    RustLib.instance.api.crateApiPatternGetPatterns();

Future<UiNote> addNote({
  required int patternId,
  required int key,
  required int startTick,
  int? duration,
}) => RustLib.instance.api.crateApiPatternAddNote(
  patternId: patternId,
  key: key,
  startTick: startTick,
  duration: duration,
);

Future<UiNote> deleteNote({required int patternId, required int noteId}) =>
    RustLib.instance.api.crateApiPatternDeleteNote(
      patternId: patternId,
      noteId: noteId,
    );

Future<UiNote> resizeNote({
  required int patternId,
  required int noteId,
  required int newDuration,
}) => RustLib.instance.api.crateApiPatternResizeNote(
  patternId: patternId,
  noteId: noteId,
  newDuration: newDuration,
);

Future<UiNote> moveNote({
  required int patternId,
  required int noteId,
  required int newStartTick,
  required int newKey,
}) => RustLib.instance.api.crateApiPatternMoveNote(
  patternId: patternId,
  noteId: noteId,
  newStartTick: newStartTick,
  newKey: newKey,
);

Future<UiNote> changeNoteParams({
  required int patternId,
  required int noteId,
  int? velocity,
  double? probability,
  int? microOffset,
  bool? mute,
}) => RustLib.instance.api.crateApiPatternChangeNoteParams(
  patternId: patternId,
  noteId: noteId,
  velocity: velocity,
  probability: probability,
  microOffset: microOffset,
  mute: mute,
);

/// Add notes in batch
///
/// ## Parameters
/// * pattern_id: [u32], id of the pattern
/// * new_notes: Vector of tuples that contains (key, start_tick, duration)
Future<void> addNotesBatch({
  required int patternId,
  required List<(int, int, int?)> notes,
}) => RustLib.instance.api.crateApiPatternAddNotesBatch(
  patternId: patternId,
  notes: notes,
);

/// Delete notes in batch
///
/// ## Parameters
/// * pattern_id: [u32], id of the pattern
/// * note_ids: Vector of notes ID to delete
Future<void> deleteNotesBatch({
  required int patternId,
  required List<int> noteIds,
}) => RustLib.instance.api.crateApiPatternDeleteNotesBatch(
  patternId: patternId,
  noteIds: noteIds,
);

/// Move notes in batch
///
/// ## Parameters
/// * pattern_id: [u32], id of the pattern
/// * note_ids: Vector of notes updates (id, )
Future<void> moveNotesBatch({
  required int patternId,
  required List<(int, int, int)> updates,
}) => RustLib.instance.api.crateApiPatternMoveNotesBatch(
  patternId: patternId,
  updates: updates,
);

Future<void> resizeNotesBatch({
  required int patternId,
  required List<(int, int)> updates,
}) => RustLib.instance.api.crateApiPatternResizeNotesBatch(
  patternId: patternId,
  updates: updates,
);

/// Play a pattern in isolation with a specific generator (looping automatically).
/// This temporarily switches the engine to Pattern playback mode.
Future<void> playPatternPreview({
  required int patternId,
  required int generatorId,
}) => RustLib.instance.api.crateApiPatternPlayPatternPreview(
  patternId: patternId,
  generatorId: generatorId,
);

/// Stop pattern preview without changing song mode. used in stop button inside pattern playback
Future<void> stopPatternPreviewLocal({
  required int patternId,
  required int generatorId,
}) => RustLib.instance.api.crateApiPatternStopPatternPreviewLocal(
  patternId: patternId,
  generatorId: generatorId,
);

/// Stop pattern preview and return to Song mode.
Future<void> stopPatternPreview() =>
    RustLib.instance.api.crateApiPatternStopPatternPreview();

@freezed
sealed class UiNote with _$UiNote {
  const factory UiNote({
    required int id,
    required int startTick,
    required int duration,
    required int key,
    required int velocity,
    required double probability,
    required int microOffset,
    required bool mute,
  }) = _UiNote;
}

@freezed
sealed class UiPattern with _$UiPattern {
  const factory UiPattern({
    required int id,
    required String name,
    required int lengthTicks,
    required List<UiNote> notes,
  }) = _UiPattern;
}
