// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mixer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'project.dart';
part 'plugin.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UiEffectParameterSnapshot`, `UiGeneratorParameterSnapshot`, `UiParameterValue`, `UiPluginCommandResponse`, `UiZeroCopyBufferResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `hash`, `into_id`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_info_to_effect`, `from_info_to_synth`, `parse_plugin_response`

/// Get all available generators with their registry IDs (preferred for UI)
Future<List<UiPluginInfo>> getAvailableGeneratorsWithIds({
  required DawContext ctx,
}) =>
    RustLib.instance.api.crateApiPluginGetAvailableGeneratorsWithIds(ctx: ctx);

/// Get all available effects with their registry IDs (preferred for UI)
Future<List<UiPluginInfo>> getAvailableEffectsWithIds({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiPluginGetAvailableEffectsWithIds(ctx: ctx);

Future<List<UiPluginInfo>> getAvailablePluginsWithIds({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiPluginGetAvailablePluginsWithIds(ctx: ctx);

/// Get a single generator state from the Generator Pool
Future<UiGeneratorInstance> getGenerator({
  required DawContext ctx,
  required int generatorId,
}) => RustLib.instance.api.crateApiPluginGetGenerator(
  ctx: ctx,
  generatorId: generatorId,
);

Future<UiEffectInstance> getEffect({
  required DawContext ctx,
  required int trackId,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffect(
  ctx: ctx,
  trackId: trackId,
  effectId: effectId,
);

Future<UiEffectInstance> getEffectFromMaster({
  required DawContext ctx,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffectFromMaster(
  ctx: ctx,
  effectId: effectId,
);

Future<List<UiEffectInstance>> getEffectsFromTrack({
  required DawContext ctx,
  required int trackId,
}) => RustLib.instance.api.crateApiPluginGetEffectsFromTrack(
  ctx: ctx,
  trackId: trackId,
);

Future<List<UiEffectInstance>> getMasterEffects({required DawContext ctx}) =>
    RustLib.instance.api.crateApiPluginGetMasterEffects(ctx: ctx);

/// Get parameter specifications for a generator plugin.
Future<List<UiPluginParameter>> getGeneratorParameterSpecs({
  required DawContext ctx,
  required int generatorId,
}) => RustLib.instance.api.crateApiPluginGetGeneratorParameterSpecs(
  ctx: ctx,
  generatorId: generatorId,
);

/// Set a parameter on a generator plugin.
Future<void> setGeneratorParameter({
  required DawContext ctx,
  required int generatorId,
  required UiParamId paramId,
  required double value,
}) => RustLib.instance.api.crateApiPluginSetGeneratorParameter(
  ctx: ctx,
  generatorId: generatorId,
  paramId: paramId,
  value: value,
);

/// Get a parameter value from a generator plugin.
Future<double> getGeneratorParameter({
  required int generatorId,
  required UiParamId paramId,
}) => RustLib.instance.api.crateApiPluginGetGeneratorParameter(
  generatorId: generatorId,
  paramId: paramId,
);

/// Request a parameter snapshot from the audio thread.
Future<void> queryGeneratorParameters({
  required DawContext ctx,
  required int generatorId,
}) => RustLib.instance.api.crateApiPluginQueryGeneratorParameters(
  ctx: ctx,
  generatorId: generatorId,
);

Future<List<UiPluginParameter>> getEffectParameterSpecs({
  required DawContext ctx,
  required UiEffectTarget target,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffectParameterSpecs(
  ctx: ctx,
  target: target,
  effectId: effectId,
);

Future<void> setEffectParameter({
  required DawContext ctx,
  required UiEffectTarget target,
  required int effectId,
  required UiParamId paramId,
  required double value,
}) => RustLib.instance.api.crateApiPluginSetEffectParameter(
  ctx: ctx,
  target: target,
  effectId: effectId,
  paramId: paramId,
  value: value,
);

Future<void> queryEffectParameters({
  required DawContext ctx,
  required UiEffectTarget target,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginQueryEffectParameters(
  ctx: ctx,
  target: target,
  effectId: effectId,
);

Future<String?> executePluginCommandGenerator({
  required DawContext ctx,
  required int genRegistryId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecutePluginCommandGenerator(
  ctx: ctx,
  genRegistryId: genRegistryId,
  command: command,
  payloadJson: payloadJson,
);

Future<String?> executePluginCommandEffect({
  required DawContext ctx,
  required int effectRegistryId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecutePluginCommandEffect(
  ctx: ctx,
  effectRegistryId: effectRegistryId,
  command: command,
  payloadJson: payloadJson,
);

Future<String> executeEffectInstanceCommand({
  required DawContext ctx,
  required UiEffectTarget target,
  required int effectId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecuteEffectInstanceCommand(
  ctx: ctx,
  target: target,
  effectId: effectId,
  command: command,
  payloadJson: payloadJson,
);

Future<String> executeGeneratorInstanceCommand({
  required DawContext ctx,
  required int generatorId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecuteGeneratorInstanceCommand(
  ctx: ctx,
  generatorId: generatorId,
  command: command,
  payloadJson: payloadJson,
);

/// Dispatches a real-time command to a live plugin instance on the audio thread.
///
/// The plugin's `execute_custom_command` is called from within the audio callback,
/// so the command and payload must be cheap to process. The response arrives
/// asynchronously via the `StreamSink` opened by `create_plugin_message_stream`.
///
/// # Parameters
/// - `target`: Which plugin instance to target.
/// - `command`: Command key string (e.g. `"get_meter"`, `"get_spectrum"`).
/// - `payload_json`: JSON string sent as the command argument. Defaults to `{}`
///   if the string is not valid JSON.
///
/// # Returns
/// `Ok(request_id)` — correlate this with `UiPluginCommandResponse.request_id`
/// in the stream. Returns `Err` if the audio stream is not active or the
/// command queue is full.
Future<int> executeRealtimePluginCommand({
  required DawContext ctx,
  required UiPluginTarget target,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecuteRealtimePluginCommand(
  ctx: ctx,
  target: target,
  command: command,
  payloadJson: payloadJson,
);

/// Dispatches a request to the audio thread to fetch a zero-copy buffer from a live plugin.
///
/// # Parameters
/// - `target`: Which plugin instance to target.
/// - `name`: The requested buffer name (e.g., `"magnitude"` or `"spectrum"`).
///
/// # Returns
/// `Ok(request_id)` — correlate this with `UiZeroCopyBufferResponse.request_id` in the stream.
Future<int> queryLivePluginZeroCopyBuf({
  required DawContext ctx,
  required UiPluginTarget target,
  required String name,
}) => RustLib.instance.api.crateApiPluginQueryLivePluginZeroCopyBuf(
  ctx: ctx,
  target: target,
  name: name,
);

/// Begin a parameter edit from user touch, or other input
///
/// This will flag the affected plugin parameter as edited.
///
/// The behavior during which the plugin's parameter are
/// edited, are determined by the plugin's internal implementation
Future<void> beginGeneratorParameterEdit({
  required DawContext ctx,
  required int generatorId,
  required UiParamId paramId,
}) => RustLib.instance.api.crateApiPluginBeginGeneratorParameterEdit(
  ctx: ctx,
  generatorId: generatorId,
  paramId: paramId,
);

/// Begin a parameter edit from user touch, or other input
///
/// This will flag the affected plugin parameter as unedited.
///
/// The behavior during which the plugin's parameter are
/// edited, are determined by the plugin's internal implementation
Future<void> endGeneratorParameterEdit({
  required DawContext ctx,
  required int generatorId,
  required UiParamId paramId,
}) => RustLib.instance.api.crateApiPluginEndGeneratorParameterEdit(
  ctx: ctx,
  generatorId: generatorId,
  paramId: paramId,
);

/// Begin a parameter edit from user touch, or other input
///
/// This will flag the affected plugin parameter as edited.
///
/// The behavior during which the plugin's parameter are
/// edited, are determined by the plugin's internal implementation
Future<void> beginEffectParameterEdit({
  required DawContext ctx,
  required UiEffectTarget effectTarget,
  required int effectId,
  required UiParamId paramId,
}) => RustLib.instance.api.crateApiPluginBeginEffectParameterEdit(
  ctx: ctx,
  effectTarget: effectTarget,
  effectId: effectId,
  paramId: paramId,
);

/// Begin a parameter edit from user touch, or other input
///
/// This will flag the affected plugin parameter as unedited.
///
/// The behavior during which the plugin's parameter are
/// edited, are determined by the plugin's internal implementation
Future<void> endEffectParameterEdit({
  required DawContext ctx,
  required UiEffectTarget effectTarget,
  required int effectId,
  required UiParamId paramId,
}) => RustLib.instance.api.crateApiPluginEndEffectParameterEdit(
  ctx: ctx,
  effectTarget: effectTarget,
  effectId: effectId,
  paramId: paramId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginBufferHandle>>
abstract class PluginBufferHandle implements RustOpaqueInterface {
  /// Reads the current buffer state directly into a Dart Float32List.
  /// This bypasses JSON entirely and takes less than a microsecond.
  Float32List read();
}

enum KarbeatPluginType { generator, effect }

@freezed
sealed class UiEffectTarget with _$UiEffectTarget {
  const UiEffectTarget._();

  const factory UiEffectTarget.track(int field0) = UiEffectTarget_Track;
  const factory UiEffectTarget.master() = UiEffectTarget_Master;
  const factory UiEffectTarget.bus(int field0) = UiEffectTarget_Bus;
}

@freezed
sealed class UiParamId with _$UiParamId {
  const UiParamId._();

  const factory UiParamId.id(int field0) = UiParamId_Id;
  const factory UiParamId.path(String field0) = UiParamId_Path;

  /// Resolves the FRB enum into the raw u32 hash expected by the audio thread
  Future<int> resolve() =>
      RustLib.instance.api.crateApiPluginUiParamIdResolve(that: this);
}

/// Parameter type enum for FRB
enum UiParameterType { float, int, bool, choice }

@freezed
sealed class UiPluginInfo with _$UiPluginInfo {
  const factory UiPluginInfo({
    required int id,
    required String name,
    required KarbeatPluginType pluginType,
  }) = _UiPluginInfo;
}

/// Plugin parameter description for UI generation
@freezed
sealed class UiPluginParameter with _$UiPluginParameter {
  const factory UiPluginParameter({
    required int id,
    required String path,
    required String name,
    required String group,
    required double value,
    required double min,
    required double max,
    required double defaultValue,
    required double step,
    required UiParameterType paramType,
    required List<String> choices,
  }) = _UiPluginParameter;
}

@freezed
sealed class UiPluginTarget with _$UiPluginTarget {
  const UiPluginTarget._();

  /// A generator plugin identified by its GeneratorId
  const factory UiPluginTarget.generator(int field0) = UiPluginTarget_Generator;

  /// A track effect identified by (TrackId, EffectId)
  const factory UiPluginTarget.trackEffect({
    required int trackId,
    required int effectId,
  }) = UiPluginTarget_TrackEffect;

  /// A bus effect identified by (BusId, EffectId)
  const factory UiPluginTarget.busEffect({
    required int busId,
    required int effectId,
  }) = UiPluginTarget_BusEffect;

  /// An effect on the master bus
  const factory UiPluginTarget.masterEffect(int field0) =
      UiPluginTarget_MasterEffect;
}
