// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mixer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'plugins/opaque.dart';
import 'plugins/types.dart';
import 'project.dart';
part 'plugin.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UiPluginCommandResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `hash`, `into_id`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_info_to_effect`, `from_info_to_synth`, `parse_plugin_response`

/// Get all available generators with their registry IDs (preferred for UI)
Future<List<UiPluginInfo>> getAvailableGeneratorsWithIds({
  required DawContext ctx,
}) =>
    RustLib.instance.api.crateApiPluginGetAvailableGeneratorsWithIds(ctx: ctx);

/// Get all available effects with their registry IDs (preferred for UI)
Future<List<UiPluginInfo>> getAvailableEffectsWithIds({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiPluginGetAvailableEffectsWithIds(ctx: ctx);

Future<List<UiPluginInfo>> getAvailablePluginsWithIds({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiPluginGetAvailablePluginsWithIds(ctx: ctx);

/// Get a single generator state from the Generator Pool
Future<UiGeneratorInstance> getGenerator({
  required DawContext ctx,
  required int generatorId,
}) => RustLib.instance.api.crateApiPluginGetGenerator(
  ctx: ctx,
  generatorId: generatorId,
);

Future<UiEffectInstance> getEffect({
  required DawContext ctx,
  required int trackId,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffect(
  ctx: ctx,
  trackId: trackId,
  effectId: effectId,
);

Future<UiEffectInstance> getEffectFromMaster({
  required DawContext ctx,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffectFromMaster(
  ctx: ctx,
  effectId: effectId,
);

Future<List<UiEffectInstance>> getEffectsFromTrack({
  required DawContext ctx,
  required int trackId,
}) => RustLib.instance.api.crateApiPluginGetEffectsFromTrack(
  ctx: ctx,
  trackId: trackId,
);

Future<List<UiEffectInstance>> getMasterEffects({required DawContext ctx}) =>
    RustLib.instance.api.crateApiPluginGetMasterEffects(ctx: ctx);

/// Get parameter specifications for ANY plugin type (Generator or Effect)
Future<List<UiPluginParameter>> getPluginParameterSpecs({
  required DawContext ctx,
  required UiPluginTarget target,
}) => RustLib.instance.api.crateApiPluginGetPluginParameterSpecs(
  ctx: ctx,
  target: target,
);

/// Set a parameter on ANY plugin type (Generator or Effect)
Future<void> setPluginParameter({
  required DawContext ctx,
  required UiPluginTarget target,
  required UiParamId paramId,
  required double value,
}) => RustLib.instance.api.crateApiPluginSetPluginParameter(
  ctx: ctx,
  target: target,
  paramId: paramId,
  value: value,
);

/// Signals the start of a parameter edit gesture (e.g., user clicks a knob)
Future<void> beginPluginParameterEdit({
  required DawContext ctx,
  required UiPluginTarget target,
  required UiParamId paramId,
}) => RustLib.instance.api.crateApiPluginBeginPluginParameterEdit(
  ctx: ctx,
  target: target,
  paramId: paramId,
);

/// Signals the end of a parameter edit gesture (e.g., user releases a knob)
Future<void> endPluginParameterEdit({
  required DawContext ctx,
  required UiPluginTarget target,
  required UiParamId paramId,
}) => RustLib.instance.api.crateApiPluginEndPluginParameterEdit(
  ctx: ctx,
  target: target,
  paramId: paramId,
);

/// 1. STATELESS COMMANDS (Operates on defaults from the Registry)
Future<String?> executePluginCommandByRegistryId({
  required DawContext ctx,
  required int registryId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecutePluginCommandByRegistryId(
  ctx: ctx,
  registryId: registryId,
  command: command,
  payloadJson: payloadJson,
);

/// 2. STATEFUL COMMANDS (Operates on active instances via Main Thread Sync)
Future<String> executePluginInstanceCommand({
  required DawContext ctx,
  required UiPluginTarget target,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecutePluginInstanceCommand(
  ctx: ctx,
  target: target,
  command: command,
  payloadJson: payloadJson,
);

/// 3. REAL-TIME COMMANDS (Dispatched to the audio thread)
Future<int> executeLivePluginCommand({
  required DawContext ctx,
  required UiPluginTarget target,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecuteLivePluginCommand(
  ctx: ctx,
  target: target,
  command: command,
  payloadJson: payloadJson,
);

/// Get the snapshot telemetry from the audio engine.
/// This utilizes an atomic ArcSwap which enables lock-free reading.
/// If empty, it means that the snapshot is not currently available.
PluginTelemetrySnapshotDto? getPluginSnapshotTelemetrySync({
  required DawContext ctx,
  required UiPluginTarget target,
}) => RustLib.instance.api.crateApiPluginGetPluginSnapshotTelemetrySync(
  ctx: ctx,
  target: target,
);

/// Start or stop the telemetry packing for a specific plugin on the audio thread.
Future<void> setPluginTelemetrySubs({
  required DawContext ctx,
  required UiPluginTarget target,
  required List<String> buffers,
  required bool active,
}) => RustLib.instance.api.crateApiPluginSetPluginTelemetrySubs(
  ctx: ctx,
  target: target,
  buffers: buffers,
  active: active,
);

enum KarbeatPluginType { generator, effect }

@freezed
sealed class UiParamId with _$UiParamId {
  const UiParamId._();

  const factory UiParamId.id(int field0) = UiParamId_Id;
  const factory UiParamId.path(String field0) = UiParamId_Path;

  /// Resolves the FRB enum into the raw u32 hash expected by the audio thread
  Future<int> resolve() =>
      RustLib.instance.api.crateApiPluginUiParamIdResolve(that: this);
}

/// Parameter type enum for FRB
enum UiParameterType { float, int, bool, choice }

@freezed
sealed class UiPluginInfo with _$UiPluginInfo {
  const factory UiPluginInfo({
    required int id,
    required String name,
    required KarbeatPluginType pluginType,
  }) = _UiPluginInfo;
}

/// Plugin parameter description for UI generation
@freezed
sealed class UiPluginParameter with _$UiPluginParameter {
  const factory UiPluginParameter({
    required int id,
    required String path,
    required String name,
    required String group,
    required double value,
    required double min,
    required double max,
    required double defaultValue,
    required double step,
    required UiParameterType paramType,
    required List<String> choices,
  }) = _UiPluginParameter;
}

@freezed
sealed class UiPluginTarget with _$UiPluginTarget {
  const UiPluginTarget._();

  /// A generator plugin identified by its GeneratorId
  const factory UiPluginTarget.generator(int field0) = UiPluginTarget_Generator;

  /// A track effect identified by (TrackId, EffectId)
  const factory UiPluginTarget.trackEffect({
    required int trackId,
    required int effectId,
  }) = UiPluginTarget_TrackEffect;

  /// A bus effect identified by (BusId, EffectId)
  const factory UiPluginTarget.busEffect({
    required int busId,
    required int effectId,
  }) = UiPluginTarget_BusEffect;

  /// An effect on the master bus
  const factory UiPluginTarget.masterEffect(int field0) =
      UiPluginTarget_MasterEffect;
}
