// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mixer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'plugins/opaque.dart';
import 'project.dart';
part 'plugin.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `hash`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_info_to_effect`, `from_info_to_synth`, `parse_plugin_response`

/// Get all available generators with their registry IDs (preferred for UI)
Future<List<UiPluginInfo>> getAvailableGeneratorsWithIds() =>
    RustLib.instance.api.crateApiPluginGetAvailableGeneratorsWithIds();

/// Get all available effects with their registry IDs (preferred for UI)
Future<List<UiPluginInfo>> getAvailableEffectsWithIds() =>
    RustLib.instance.api.crateApiPluginGetAvailableEffectsWithIds();

/// Get a single generator state from the Generator Pool
Future<UiGeneratorInstance> getGenerator({required int generatorId}) =>
    RustLib.instance.api.crateApiPluginGetGenerator(generatorId: generatorId);

Future<UiEffectInstance> getEffect({
  required int trackId,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffect(
  trackId: trackId,
  effectId: effectId,
);

Future<UiEffectInstance> getEffectFromMaster({required int effectId}) =>
    RustLib.instance.api.crateApiPluginGetEffectFromMaster(effectId: effectId);

Future<List<UiEffectInstance>> getEffectsFromTrack({required int trackId}) =>
    RustLib.instance.api.crateApiPluginGetEffectsFromTrack(trackId: trackId);

Future<List<UiEffectInstance>> getMasterEffects() =>
    RustLib.instance.api.crateApiPluginGetMasterEffects();

/// Get parameter specifications for a generator plugin.
Future<List<UiPluginParameter>> getGeneratorParameterSpecs({
  required int generatorId,
}) => RustLib.instance.api.crateApiPluginGetGeneratorParameterSpecs(
  generatorId: generatorId,
);

/// Set a parameter on a generator plugin.
Future<void> setGeneratorParameter({
  required int generatorId,
  required UiParamId paramId,
  required double value,
}) => RustLib.instance.api.crateApiPluginSetGeneratorParameter(
  generatorId: generatorId,
  paramId: paramId,
  value: value,
);

/// Get a parameter value from a generator plugin.
Future<double> getGeneratorParameter({
  required int generatorId,
  required UiParamId paramId,
}) => RustLib.instance.api.crateApiPluginGetGeneratorParameter(
  generatorId: generatorId,
  paramId: paramId,
);

/// Request a parameter snapshot from the audio thread.
Future<void> queryGeneratorParameters({required int generatorId}) => RustLib
    .instance
    .api
    .crateApiPluginQueryGeneratorParameters(generatorId: generatorId);

/// Poll for parameter feedback from the audio thread.
Future<List<UiGeneratorParameterSnapshot>> pollGeneratorParameterFeedback() =>
    RustLib.instance.api.crateApiPluginPollGeneratorParameterFeedback();

Future<List<UiEffectParameterSnapshot>> pollEffectParameterFeedback() =>
    RustLib.instance.api.crateApiPluginPollEffectParameterFeedback();

Future<List<UiPluginParameter>> getEffectParameterSpecs({
  required UiEffectTarget target,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffectParameterSpecs(
  target: target,
  effectId: effectId,
);

Future<void> setEffectParameter({
  required UiEffectTarget target,
  required int effectId,
  required UiParamId paramId,
  required double value,
}) => RustLib.instance.api.crateApiPluginSetEffectParameter(
  target: target,
  effectId: effectId,
  paramId: paramId,
  value: value,
);

Future<void> queryEffectParameters({
  required UiEffectTarget target,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginQueryEffectParameters(
  target: target,
  effectId: effectId,
);

Future<String?> executePluginCommandGenerator({
  required int genRegistryId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecutePluginCommandGenerator(
  genRegistryId: genRegistryId,
  command: command,
  payloadJson: payloadJson,
);

Future<String?> executePluginCommandEffect({
  required int effectRegistryId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecutePluginCommandEffect(
  effectRegistryId: effectRegistryId,
  command: command,
  payloadJson: payloadJson,
);

Future<String> executeEffectInstanceCommand({
  required UiEffectTarget target,
  required int effectId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecuteEffectInstanceCommand(
  target: target,
  effectId: effectId,
  command: command,
  payloadJson: payloadJson,
);

Future<String> executeGeneratorInstanceCommand({
  required int generatorId,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecuteGeneratorInstanceCommand(
  generatorId: generatorId,
  command: command,
  payloadJson: payloadJson,
);

/// Dispatches a real-time command to a live plugin instance on the audio thread.
///
/// The plugin's `execute_custom_command` is called from within the audio callback,
/// so the command and payload must be cheap to process. The response arrives
/// asynchronously via the `StreamSink` opened by `create_plugin_message_stream`.
///
/// # Parameters
/// - `target`: Which plugin instance to target.
/// - `command`: Command key string (e.g. `"get_meter"`, `"get_spectrum"`).
/// - `payload_json`: JSON string sent as the command argument. Defaults to `{}`
///   if the string is not valid JSON.
///
/// # Returns
/// `Ok(request_id)` — correlate this with `UiPluginCommandResponse.request_id`
/// in the stream. Returns `Err` if the audio stream is not active or the
/// command queue is full.
Future<int> executeRealtimePluginCommand({
  required UiPluginTarget target,
  required String command,
  required String payloadJson,
}) => RustLib.instance.api.crateApiPluginExecuteRealtimePluginCommand(
  target: target,
  command: command,
  payloadJson: payloadJson,
);

/// Opens a stream that continuously polls the audio→UI feedback channel and
/// forwards any `PluginCommandResponse` messages to Flutter.
///
/// Flutter can subscribe to this stream with a `StreamBuilder<UiPluginCommandResponse>`
/// and use `response.request_id` to match responses to pending commands.
///
/// The polling thread runs at ~16ms intervals (≈60fps). It terminates
/// automatically when Flutter closes the stream (sink returns an error).
Stream<UiPluginCommandResponse> createPluginMessageStream() =>
    RustLib.instance.api.crateApiPluginCreatePluginMessageStream();

/// Dispatches a request to the audio thread to fetch a zero-copy buffer from a live plugin.
///
/// # Parameters
/// - `target`: Which plugin instance to target.
/// - `name`: The requested buffer name (e.g., `"magnitude"` or `"spectrum"`).
///
/// # Returns
/// `Ok(request_id)` — correlate this with `UiZeroCopyBufferResponse.request_id` in the stream.
Future<int> queryLivePluginZeroCopyBuf({
  required UiPluginTarget target,
  required String name,
}) => RustLib.instance.api.crateApiPluginQueryLivePluginZeroCopyBuf(
  target: target,
  name: name,
);

/// Opens a stream that continuously polls the audio→UI feedback channel and
/// forwards any requested `ZeroCopyBuffer` handles to Flutter.
///
/// The polling thread runs at ~16ms intervals (≈60fps). It terminates
/// automatically when Flutter closes the stream.
Stream<UiZeroCopyBufferResponse> createZeroCopyBufferStream() =>
    RustLib.instance.api.crateApiPluginCreateZeroCopyBufferStream();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginBufferHandle>>
abstract class PluginBufferHandle implements RustOpaqueInterface {
  /// Reads the current buffer state directly into a Dart Float32List.
  /// This bypasses JSON entirely and takes less than a microsecond.
  Float32List read();
}

enum KarbeatPluginType { generator, effect }

@freezed
sealed class UiEffectParameterSnapshot with _$UiEffectParameterSnapshot {
  const factory UiEffectParameterSnapshot({
    required UiEffectTarget target,
    required int effectId,
    required List<UiParameterValue> parameters,
  }) = _UiEffectParameterSnapshot;
}

@freezed
sealed class UiEffectTarget with _$UiEffectTarget {
  const UiEffectTarget._();

  const factory UiEffectTarget.track(int field0) = UiEffectTarget_Track;
  const factory UiEffectTarget.master() = UiEffectTarget_Master;
  const factory UiEffectTarget.bus(int field0) = UiEffectTarget_Bus;
}

/// Parameter snapshot from the audio thread (DTO)
@freezed
sealed class UiGeneratorParameterSnapshot with _$UiGeneratorParameterSnapshot {
  const factory UiGeneratorParameterSnapshot({
    required int generatorId,
    required List<UiParameterValue> parameters,
  }) = _UiGeneratorParameterSnapshot;
}

@freezed
sealed class UiParamId with _$UiParamId {
  const UiParamId._();

  const factory UiParamId.id(int field0) = UiParamId_Id;
  const factory UiParamId.path(String field0) = UiParamId_Path;

  /// Resolves the FRB enum into the raw u32 hash expected by the audio thread
  Future<int> resolve() =>
      RustLib.instance.api.crateApiPluginUiParamIdResolve(that: this);
}

/// Parameter type enum for FRB
enum UiParameterType { float, int, bool, choice }

/// Single parameter value from the audio thread
@freezed
sealed class UiParameterValue with _$UiParameterValue {
  const factory UiParameterValue({
    required int paramId,
    required double value,
  }) = _UiParameterValue;
}

/// A response message arriving from the audio thread to Flutter.
/// Flutter uses the `request_id` to correlate with the original command sent
/// via `execute_realtime_plugin_command`.
@freezed
sealed class UiPluginCommandResponse with _$UiPluginCommandResponse {
  const factory UiPluginCommandResponse({
    required int requestId,
    required String responseJson,
  }) = _UiPluginCommandResponse;
}

@freezed
sealed class UiPluginInfo with _$UiPluginInfo {
  const factory UiPluginInfo({
    required int id,
    required String name,
    required KarbeatPluginType pluginType,
  }) = _UiPluginInfo;
}

/// Plugin parameter description for UI generation
@freezed
sealed class UiPluginParameter with _$UiPluginParameter {
  const factory UiPluginParameter({
    required int id,
    required String path,
    required String name,
    required String group,
    required double value,
    required double min,
    required double max,
    required double defaultValue,
    required double step,
    required UiParameterType paramType,
    required List<String> choices,
  }) = _UiPluginParameter;
}

@freezed
sealed class UiPluginTarget with _$UiPluginTarget {
  const UiPluginTarget._();

  /// A generator plugin identified by its GeneratorId
  const factory UiPluginTarget.generator(int field0) = UiPluginTarget_Generator;

  /// A track effect identified by (TrackId, EffectId)
  const factory UiPluginTarget.trackEffect({
    required int trackId,
    required int effectId,
  }) = UiPluginTarget_TrackEffect;

  /// A bus effect identified by (BusId, EffectId)
  const factory UiPluginTarget.busEffect({
    required int busId,
    required int effectId,
  }) = UiPluginTarget_BusEffect;

  /// An effect on the master bus
  const factory UiPluginTarget.masterEffect(int field0) =
      UiPluginTarget_MasterEffect;
}

/// A response message arriving from the audio thread containing the zero-copy buffer.
/// Dart uses the `request_id` to correlate with the original command sent via `query_zero_copy_buffer`.
class UiZeroCopyBufferResponse {
  final int requestId;

  /// The opaque handle that Dart can use to read raw memory.
  /// It is `None` if the plugin did not recognize the buffer name.
  final ZeroCopyHandle? handle;

  const UiZeroCopyBufferResponse({required this.requestId, this.handle});

  @override
  int get hashCode => requestId.hashCode ^ handle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiZeroCopyBufferResponse &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          handle == other.handle;
}
