// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mixer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'pattern.dart';
import 'waveform.dart';
part 'project.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_track`

UiProjectMetadata projectMetadataNew() =>
    RustLib.instance.api.crateApiProjectProjectMetadataNew();

UiAudioHardwareConfig audioHardwareConfigNew() =>
    RustLib.instance.api.crateApiProjectAudioHardwareConfigNew();

UiAudioHardwareConfig audioHardwareConfigNewWithParam({
  required String selectedInputDevice,
  required String selectedOutputDevice,
  required int sampleRate,
  required int bufferSize,
  required double cpuLoad,
}) => RustLib.instance.api.crateApiProjectAudioHardwareConfigNewWithParam(
  selectedInputDevice: selectedInputDevice,
  selectedOutputDevice: selectedOutputDevice,
  sampleRate: sampleRate,
  bufferSize: bufferSize,
  cpuLoad: cpuLoad,
);

UiTransportState transportStateNew() =>
    RustLib.instance.api.crateApiProjectTransportStateNew();

UiTransportState transportStateNewWithParam({
  required double bpm,
  required (int, int) timeSignature,
}) => RustLib.instance.api.crateApiProjectTransportStateNewWithParam(
  bpm: bpm,
  timeSignature: timeSignature,
);

/// Get the current project metadata state from the backend
Future<UiProjectMetadata> getProjectMetadata({required DawContext ctx}) =>
    RustLib.instance.api.crateApiProjectGetProjectMetadata(ctx: ctx);

/// Get the transport state from the backend
Future<UiTransportState> getTransportState({required DawContext ctx}) =>
    RustLib.instance.api.crateApiProjectGetTransportState(ctx: ctx);

/// Get all audio waveform source list from the backend
Future<Map<int, AudioWaveformUiForSourceList>?> getAudioSourceList({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiProjectGetAudioSourceList(ctx: ctx);

/// Get generator list used in the project
Future<Map<int, UiGeneratorInstance>> getGeneratorList({
  required DawContext ctx,
}) => RustLib.instance.api.crateApiProjectGetGeneratorList(ctx: ctx);

/// Add a new audio source to the project
///
/// ## Parameters:
/// - file_path: Path to the audio file to be added
Future<int> addAudioSource({
  required DawContext ctx,
  required String filePath,
}) => RustLib.instance.api.crateApiProjectAddAudioSource(
  ctx: ctx,
  filePath: filePath,
);

/// Add new track to the track list. Throws an error, so it must handled gracefully
Future<UiTrack> addNewAudioTrack({required DawContext ctx}) =>
    RustLib.instance.api.crateApiProjectAddNewAudioTrack(ctx: ctx);

/// Get all tracks on the session/project.
///
/// Returns Map<u32, UiTrack> upon success, and Error when it fails
Future<Map<int, UiTrack>> getTracks({required DawContext ctx}) =>
    RustLib.instance.api.crateApiProjectGetTracks(ctx: ctx);

/// Export project to flutter. also report progress via StreamSink
Stream<double> exportProjectFlutter({
  required DawContext ctx,
  required String outputPath,
  required AudioExportConfigDTO config,
  required TailHandlingDTO tailHandling,
}) => RustLib.instance.api.crateApiProjectExportProjectFlutter(
  ctx: ctx,
  outputPath: outputPath,
  config: config,
  tailHandling: tailHandling,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioWaveform>>
abstract class AudioWaveform implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioWaveformUiForAudioProperties>>
abstract class AudioWaveformUiForAudioProperties
    implements RustOpaqueInterface {
  WaveformHandle get bufferHandle;

  int get channels;

  double get duration;

  String get filePath;

  int get fineTune;

  int? get id;

  bool get isLooping;

  bool get muted;

  String get name;

  bool get normalized;

  int get rootNote;

  int get sampleRate;

  int get trimEnd;

  int get trimStart;

  set bufferHandle(WaveformHandle bufferHandle);

  set channels(int channels);

  set duration(double duration);

  set filePath(String filePath);

  set fineTune(int fineTune);

  set id(int? id);

  set isLooping(bool isLooping);

  set muted(bool muted);

  set name(String name);

  set normalized(bool normalized);

  set rootNote(int rootNote);

  set sampleRate(int sampleRate);

  set trimEnd(int trimEnd);

  set trimStart(int trimStart);

  static Future<AudioWaveformUiForAudioProperties> tryFromWithContext({
    required DawContext ctx,
    required AudioWaveform value,
  }) => RustLib.instance.api
      .crateApiProjectAudioWaveformUiForAudioPropertiesTryFromWithContext(
        ctx: ctx,
        value: value,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DawContext>>
abstract class DawContext implements RustOpaqueInterface {}

@freezed
sealed class AudioExportConfigDTO with _$AudioExportConfigDTO {
  const AudioExportConfigDTO._();

  const factory AudioExportConfigDTO.wav(WavExportConfigDTO field0) =
      AudioExportConfigDTO_Wav;
  const factory AudioExportConfigDTO.mp3(Mp3ExportConfigDTO field0) =
      AudioExportConfigDTO_Mp3;
}

@freezed
sealed class AudioWaveformUiForSourceList with _$AudioWaveformUiForSourceList {
  const factory AudioWaveformUiForSourceList({
    required String name,
    required bool muted,
    required int sampleRate,
  }) = _AudioWaveformUiForSourceList;
}

@freezed
sealed class BitDepthDTO with _$BitDepthDTO {
  const BitDepthDTO._();

  const factory BitDepthDTO.bitPerSample(int field0) = BitDepthDTO_BitPerSample;
  const factory BitDepthDTO.bitPerSecond(int field0) = BitDepthDTO_BitPerSecond;
}

class Mp3ExportConfigDTO {
  final int sampleRate;
  final int channels;
  final BitDepthDTO bitRate;

  const Mp3ExportConfigDTO({
    required this.sampleRate,
    required this.channels,
    required this.bitRate,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^ channels.hashCode ^ bitRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Mp3ExportConfigDTO &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitRate == other.bitRate;
}

enum TailHandlingDTO { cutRemaining, leaveRemaining, wrapRemaining }

class UiApplicationState {
  final UiProjectMetadata metadata;
  final UiTransportState transport;
  final UiAudioHardwareConfig hardwareConfig;
  final Map<int, UiTrack> tracks;
  final Map<int, UiGeneratorInstance> generators;
  final Map<int, UiPattern> patterns;
  final UiMixerState mixer;
  final Map<int, AudioWaveformUiForSourceList> audioSources;

  const UiApplicationState({
    required this.metadata,
    required this.transport,
    required this.hardwareConfig,
    required this.tracks,
    required this.generators,
    required this.patterns,
    required this.mixer,
    required this.audioSources,
  });

  @override
  int get hashCode =>
      metadata.hashCode ^
      transport.hashCode ^
      hardwareConfig.hashCode ^
      tracks.hashCode ^
      generators.hashCode ^
      patterns.hashCode ^
      mixer.hashCode ^
      audioSources.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiApplicationState &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          transport == other.transport &&
          hardwareConfig == other.hardwareConfig &&
          tracks == other.tracks &&
          generators == other.generators &&
          patterns == other.patterns &&
          mixer == other.mixer &&
          audioSources == other.audioSources;
}

@freezed
sealed class UiAudioHardwareConfig with _$UiAudioHardwareConfig {
  const factory UiAudioHardwareConfig({
    required String selectedInputDevice,
    required String selectedOutputDevice,
    required int sampleRate,
    required int bufferSize,
    required double cpuLoad,
  }) = _UiAudioHardwareConfig;
}

@freezed
sealed class UiClip with _$UiClip {
  const factory UiClip({
    required String name,
    required int id,
    required int startTime,
    required UiClipSource source,
    required int offsetStart,
    required int loopLength,
    required bool isSampleBased,
  }) = _UiClip;
}

@freezed
sealed class UiClipSource with _$UiClipSource {
  const UiClipSource._();

  const factory UiClipSource.audio({required int sourceId}) =
      UiClipSource_Audio;
  const factory UiClipSource.midi({required int patternId}) = UiClipSource_Midi;
  const factory UiClipSource.none() = UiClipSource_None;
}

@freezed
sealed class UiGeneratorInstance with _$UiGeneratorInstance {
  const factory UiGeneratorInstance({
    required int id,
    required UiGeneratorInstanceType instanceType,
  }) = _UiGeneratorInstance;
}

@freezed
sealed class UiGeneratorInstanceType with _$UiGeneratorInstanceType {
  const UiGeneratorInstanceType._();

  const factory UiGeneratorInstanceType.plugin(UiPluginInstance field0) =
      UiGeneratorInstanceType_Plugin;
  const factory UiGeneratorInstanceType.sampler({
    required int assetId,
    required int rootNote,
  }) = UiGeneratorInstanceType_Sampler;
}

@freezed
sealed class UiPluginInstance with _$UiPluginInstance {
  const factory UiPluginInstance({
    required int registryId,
    required String name,
    required bool bypass,
  }) = _UiPluginInstance;
}

@freezed
sealed class UiProjectMetadata with _$UiProjectMetadata {
  const UiProjectMetadata._();
  const factory UiProjectMetadata({
    required String name,
    required String author,
    required String version,
    required String createdAt,
  }) = _UiProjectMetadata;
  static Future<UiProjectMetadata> default_() =>
      RustLib.instance.api.crateApiProjectUiProjectMetadataDefault();
}

@freezed
sealed class UiTrack with _$UiTrack {
  const factory UiTrack({
    required int id,
    required String name,
    required String color,
    required UiTrackType trackType,
    required List<UiClip> clips,
    int? generatorId,
    required int orderIdx,
  }) = _UiTrack;
}

enum UiTrackType { audio, midi, automation }

@freezed
sealed class UiTransportState with _$UiTransportState {
  const UiTransportState._();
  const factory UiTransportState({
    required double bpm,
    required (int, int) timeSignature,
  }) = _UiTransportState;
  static Future<UiTransportState> default_() =>
      RustLib.instance.api.crateApiProjectUiTransportStateDefault();
}

class WavExportConfigDTO {
  final int sampleRate;
  final int channels;
  final BitDepthDTO bitDepth;

  const WavExportConfigDTO({
    required this.sampleRate,
    required this.channels,
    required this.bitDepth,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^ channels.hashCode ^ bitDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WavExportConfigDTO &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitDepth == other.bitDepth;
}
