// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mixer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pattern.dart';
import 'project.dart';

/// Save the currrent project to path_name
Future<void> saveProject({required DawContext ctx, required String pathName}) =>
    RustLib.instance.api.crateApiSerializationSaveProject(
      ctx: ctx,
      pathName: pathName,
    );

/// Load the `.karbeat` or `.dgdaw` project.
Future<UiApplicationState> loadProject({
  required DawContext ctx,
  required String pathName,
}) => RustLib.instance.api.crateApiSerializationLoadProject(
  ctx: ctx,
  pathName: pathName,
);

Future<UiApplicationState> newBlankProject({required DawContext ctx}) =>
    RustLib.instance.api.crateApiSerializationNewBlankProject(ctx: ctx);
