// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'automation.dart';
import 'mixer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pattern.dart';
import 'plugin.dart';
import 'project.dart';

// These functions are ignored because they are not marked as `pub`: `load_project_blocking`, `new_blank_project_blocking`, `restore_loaded_project`, `save_project_blocking`

/// Save the currrent project to path_name
Future<void> saveProject({required DawContext ctx, required String pathName}) =>
    RustLib.instance.api.crateApiSerializationSaveProject(
      ctx: ctx,
      pathName: pathName,
    );

/// Load the `.karbeat` or `.dgdaw` project.
Future<UiApplicationState> loadProject({
  required DawContext ctx,
  required String pathName,
}) => RustLib.instance.api.crateApiSerializationLoadProject(
  ctx: ctx,
  pathName: pathName,
);

Future<UiApplicationState> newBlankProject({required DawContext ctx}) =>
    RustLib.instance.api.crateApiSerializationNewBlankProject(ctx: ctx);

/// Whether the current project has no unsaved changes. Read it when the answer is needed, such
/// as before closing the window or replacing the project; it is not meant for polling.
bool isProjectSaved({required DawContext ctx}) =>
    RustLib.instance.api.crateApiSerializationIsProjectSaved(ctx: ctx);
