// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'project.dart';

DawContext createDawContext() =>
    RustLib.instance.api.crateApiSimpleCreateDawContext();

int getHistoryLimit({required DawContext ctx}) =>
    RustLib.instance.api.crateApiSimpleGetHistoryLimit(ctx: ctx);

Future<int> setHistoryLimit({required DawContext ctx, required int limit}) =>
    RustLib.instance.api.crateApiSimpleSetHistoryLimit(ctx: ctx, limit: limit);
