// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'project.dart';
part 'timeline.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `from`, `from`

/// Current loop region and cue markers.
Future<UiTimelineState> getTimelineState({required DawContext ctx}) =>
    RustLib.instance.api.crateApiTimelineGetTimelineState(ctx: ctx);

/// Sets the song loop region, or clears it with `None`.
Future<UiTimelineState> setLoopRegion({
  required DawContext ctx,
  UiLoopRegion? region,
}) => RustLib.instance.api.crateApiTimelineSetLoopRegion(
  ctx: ctx,
  region: region,
);

/// Adds a cue marker at `tick`; without a name it is numbered.
Future<UiTimelineState> addCueMarker({
  required DawContext ctx,
  required int tick,
  String? name,
}) => RustLib.instance.api.crateApiTimelineAddCueMarker(
  ctx: ctx,
  tick: tick,
  name: name,
);

/// Replaces a cue marker's name, position, and color (`#RRGGBB` or `#RRGGBBAA`).
Future<UiTimelineState> updateCueMarker({
  required DawContext ctx,
  required int id,
  required String name,
  required int tick,
  required String color,
}) => RustLib.instance.api.crateApiTimelineUpdateCueMarker(
  ctx: ctx,
  id: id,
  name: name,
  tick: tick,
  color: color,
);

/// Removes a cue marker.
Future<UiTimelineState> removeCueMarker({
  required DawContext ctx,
  required int id,
}) => RustLib.instance.api.crateApiTimelineRemoveCueMarker(ctx: ctx, id: id);

@freezed
sealed class UiCueMarker with _$UiCueMarker {
  const factory UiCueMarker({
    required int id,
    required String name,
    required int tick,
    required String color,
  }) = _UiCueMarker;
}

@freezed
sealed class UiLoopRegion with _$UiLoopRegion {
  const factory UiLoopRegion({required int startTick, required int endTick}) =
      _UiLoopRegion;
}

@freezed
sealed class UiTimelineState with _$UiTimelineState {
  const UiTimelineState._();
  const factory UiTimelineState({
    UiLoopRegion? loopRegion,
    required List<UiCueMarker> markers,
  }) = _UiTimelineState;
  static Future<UiTimelineState> default_() =>
      RustLib.instance.api.crateApiTimelineUiTimelineStateDefault();
}
