// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// set the play state of the transport
Future<void> setPlaying({required bool val}) =>
    RustLib.instance.api.crateApiTransportSetPlaying(val: val);

/// set what position the playhead is at (in samples)
Future<void> setPlayhead({required int val}) =>
    RustLib.instance.api.crateApiTransportSetPlayhead(val: val);

/// set whether the transport is looping
Future<void> setLooping({required bool val}) =>
    RustLib.instance.api.crateApiTransportSetLooping(val: val);

/// set the BPM of the transport.
/// writes to both ApplicationState (for serialization) and AudioCommand (for audio thread)
Future<void> setBpm({required double val}) =>
    RustLib.instance.api.crateApiTransportSetBpm(val: val);

/// stop the song playback and reset the playhead to 0
Future<void> stopSongPlayback() =>
    RustLib.instance.api.crateApiTransportStopSongPlayback();
