// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Helper function to acquire u32 ID from string
/// using FNV1a hash functions
int hashStrFnv1A({required String s}) =>
    RustLib.instance.api.crateApiUtilsHashStrFnv1A(s: s);
