// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'project.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Get a WaveformHandle for a single audio source by its source ID.
/// Returns None if the source does not exist in the asset library.
WaveformHandle? getWaveformHandle({
  required DawContext ctx,
  required int sourceId,
}) => RustLib.instance.api.crateApiWaveformGetWaveformHandle(
  ctx: ctx,
  sourceId: sourceId,
);

/// Returns a map of source_id → WaveformHandle for every audio clip in the
/// given track. Returns an empty map if the track does not exist, is not an
/// audio track, or contains no audio clips.
///
/// This is a sync call — it only reads Arc pointers from the app state, so
/// there is no blocking I/O and no buffer copying.
Map<int, WaveformHandle> getWaveformHandlesForTrack({
  required DawContext ctx,
  required int trackId,
}) => RustLib.instance.api.crateApiWaveformGetWaveformHandlesForTrack(
  ctx: ctx,
  trackId: trackId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WaveformHandle>>
abstract class WaveformHandle implements RustOpaqueInterface {
  /// Returns the number of channels in the audio waveform (1 = mono, 2 = stereo).
  int getChannels();

  /// Returns the total number of f32 samples in the buffer (frames × channels).
  int getLen();

  /// Returns the raw memory address of the f32 interleaved sample buffer.
  /// Returns 0 if the waveform has no loaded buffer (e.g. not yet mmap-ed).
  int getPointer();

  /// Returns the sample rate of the audio waveform (e.g. 44100, 48000).
  int getSampleRate();
}
