[package]
name = "karbeat-utils"
version = "0.3.0"
edition = "2021"
license = "LGPL-3.0-only"
description = "Auxiliary utilities for Karbeat"

[dependencies]
log.workspace = true
serde.workspace = true
thiserror.workspace = true
dasp.workspace = true
hashbrown.workspace = true
indexmap.workspace = true
serde_json.workspace = true

[lints]
workspace = true
